[msg msg_combine_PERSONA170 [Ella]]
[s]I am [clr 1][var 1][clr 27].[n][w][e]
[s]You would slay gods to protect the[n]justice you believe in... Very well.[n]Then we'll dance to the end.[n][w][e]

[msg msg_combine_PERSONA201 [Cendrillon]]
[s]I am [clr 1][var 1][clr 27].[n][w][e]
[s]Rather than accepting a life in cinders, you[n]would strive for glory? Then let me cast a[n]spell upon you...[n][w][e]

[msg msg_combine_PERSONA363 [Vanadis]]
[s]I am [clr 1][var 1][clr 27].[n][w][e]
[s]Let purity, virtue and beauty lift our wings{0A}and let us soar![n][w][e]

[msg msg_combine_PERSONA364 [Vanadis]]
[s]RESERVE[n][w][e]