[msg DVL_000_0_0 [Mysterious Voice]]
[s][vp 8 0 0 1 65535 0]I am thou, thou art I...[n][f 1 2 160][w][e]

[msg DVL_002_0_0 [Cendrillon]]
[s][vp 8 0 0 3 65535 0]Rather than accept a life[n]in cinders...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 4 65535 0]You'd strive towards splendor--[n]you know the risk.[n][f 1 3 65535][w][e]

[msg DVL_004_0_0 [Cendrillon]]
[s][vp 8 0 0 5 65535 0]So adamant...[n][f 1 3 65535][w][e]


