[msg DVL_001_0_0 [Cendrillon]]
[s][vp 8 0 0 0 6 0]I am [clr 1]Cendrillon[clr 27]—the other you who[n]exists within...[n][f 1 3 65535][w][e]

[msg DVL_002_0_0 [Cendrillon]]
[s][vp 8 0 0 0 6 0]Though I may disappear this moment,[n]I shall always be at your side.[n][f 1 3 65535][w][e]

[msg DVL_003_0_0 [Cendrillon]]
[s][vp 8 0 0 0 6 0]We shall meet again... when your fate[n]reaches its conclusion. [n][f 1 3 65535][w][e]
