# Set the ACB name the cue is from.
acb_name: 'system'

# What audio player to play audio with.
# For replacing audio besides BGM, set the ID to -1.
# -1 will inherit the player of the replaced cue.
player_id: -1

# Volume setting. Range: 0.0 to 1.0+
volume: 1.0