[msg Item_010]
[s]由觉醒之力具现化的[n]突击步枪[n][e]

[msg Item_011]
[s]基于杠杆式突击步枪[n]打造的模型枪[n][e]

[msg Item_013]
[s]某位著名伟人日常使用的[n]模型枪[n][e]

[msg Item_015]
[s]基于杠杆式突击步枪[n]打造的模型枪[n][e]

[msg Item_016]
[s]玛尼普拉[n]的升级版[n][e]

[msg Item_01B]
[s]运用古法技艺锻造的[n]模型枪[n][e]

[msg Item_01E]
[s]萨哈色拉[n]的升级版[n][e]

[msg Item_0EA]
[s]枪管中流淌着根脉轮之力的[n]模型枪[n][e]

[msg Item_0F0]
[s]绽放耀眼光芒的[n]模型枪[n][e]

[msg Item_0F4]
[s]借助脉轮之力发射[n]高威力子弹的模型枪[n][e]

[msg Item_0F6]
[s]某位著名伟人日常使用的[n]模型枪[n][e]

[msg Item_0F7]
[s]某位著名伟人日常使用的[n]模型枪[n][e]

[msg Item_0F8]
[s]偶尔会改变纹样的[n]模型枪[n][e]

[msg Item_0FB]
[s]传说能为持有者带来[n]天堂祝福的模型枪[n][e]

[msg Item_0FC]
[s]已知能释放极致威力的[n]模型枪[n][e]