[msg msg_combine_PERSONA170 [艾拉]]
[s]我是[clr 1][var 1][clr 27]。[n][w][e]
[s]为了心中正义而弑神之人……[n]很好，那便共舞至终章吧。[n][w][e]

[msg msg_combine_PERSONA201 [灰姑娘]]
[s]我是[clr 1][var 1][clr 27]。[n][w][e]
[s]与其接受化为灰烬的命运，[n]你宁可追逐荣光？[n]那便让我为你施下魔法吧……[n][w][e]

[msg msg_combine_PERSONA363 [凡娜迪丝]]
[s]我是[clr 1][var 1][clr 27]。[n][w][e]
[s]愿纯洁、美德与美丽化为吾等之翼，｛０Ａ｝展翅翱翔吧！[n][w][e]

[msg msg_combine_PERSONA364 [凡娜迪丝]]
[s]保留[n][w][e]