[msg CHK_TOILET_MEN_01]
[s][vp 1 0 0 0 0 0]这里是女厕所……[n][w][e]
[s][vp 1 0 0 0 0 0]比教学大楼的要脏不少……[n][w][e]

[msg MSG_TOILET_WOMEN_MORU [摩尔加纳]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]摩尔加纳∶[n]你知道这是男厕所吧？[n]不可以进去喔……[n][w][e]

[msg MSG_TOILET_WOMEN]
[s][vp 1 0 0 0 0 0]没有进男厕所的理由……[n][w][e]

[msg MND_E12310100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]这里是女厕所……[n][w][e]
[s][vp 1 0 0 0 0 0]比教学大楼的要脏不少……[n][w][e]

[msg MND_E12720100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]这里是女厕所……[n][w][e]
[s][vp 1 0 0 0 0 0]比教学大楼的要脏不少……[n][w][e]

[msg MND_E13710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]这里是女厕所……[n][w][e]
[s][vp 1 0 0 0 0 0]目前我在这里没有什么特别需要做的事情…[n][w][e]

[msg MND_E14130100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]这里是女厕所……[n][w][e]
[s][vp 1 0 0 0 0 0]比教学大楼的要脏不少……[n][w][e]

[msg MND_COMMON_CHK_TOILET_ME]
[s][vp 1 0 0 0 0 0]这里是女厕所……[n][w][e]
[s][vp 1 0 0 0 0 0]目前我在这里没有什么特别需要做的事情…[n][w][e]

[msg MND_E12310100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]这里是男厕所……[n][w][e]
[s][vp 1 0 0 0 0 0]还是走吧。留在这里太久可能[n]会被其他人误会……[n][w][e]

[msg MND_E12720100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]这里是男厕所……[n][w][e]
[s][vp 1 0 0 0 0 0]还是走吧。留在这里太久可能[n]会被其他人误会……[n][w][e]

[msg MND_E13710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]这里是男厕所……[n][w][e]
[s][vp 1 0 0 0 0 0]还是走吧。留在这里太久可能[n]会被其他人误会……[n][w][e]

[msg MND_E14130100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]这里是男厕所……[n][w][e]
[s][vp 1 0 0 0 0 0]还是走吧。留在这里太久可能[n]会被其他人误会……[n][w][e]

[msg MND_COMMON_CHK_TOILET_WO]
[s][vp 1 0 0 0 0 0]这里是男厕所……[n][w][e]
[s][vp 1 0 0 0 0 0]还是走吧。留在这里太久可能[n]会被其他人误会……[n][w][e]