[msg MSG_TOILET_WOMEN_MORU [摩尔加纳]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]摩尔加纳∶[n]你知道这是男厕所吧？[n]不可以进去喔……[n][w][e]

[msg MSG_TOILET_WOMEN]
[s][vp 1 0 0 0 0 0]没有进男厕所的理由……[n][w][e]

[msg MND_E12010100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]似乎是供高年级男生使用的[n]厕所。[n][w][e]
[s][vp 1 0 0 0 0 0]可以听到男生们在里面聊天……[n][w][e]

[msg MND_E12310100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]没有进男厕所的理由……[n][w][e]

[msg MND_E12720100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]没有进男厕所的理由……[n][w][e]

[msg MND_E13710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]没有进男厕所的理由……[n][w][e]

[msg MND_E14130100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]没有进男厕所的理由……[n][w][e]

[msg MND_COMMON_CHK_TOILET_WO]
[s][vp 1 0 0 0 0 0]没有进男厕所的理由……[n][w][e]

[msg MSG_E13710100_CHK_TOILET_5 [坂本　龙司]]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 2 1 7114 65535 0]哇！等下！不可以进去啊！[n]赶紧去你的教室吧！[n][w][e]