[msg MSG_199]
[f 0 5 65278][f 2 1]占位符[n][e]

[msg MSG_200]
[f 0 5 65278][f 2 1]占位符[n][e]

[msg MSG_201]
[f 0 5 65278][f 2 1]风度翩翩，优雅自如！[n]霞主角mod的主视觉图[n]由@trillmunch绘制[n][e]

[msg MSG_202]
[f 0 5 65278][f 2 1]霞主角mod的图标插图[n]由@trillmunch绘制[n][e]

[msg MSG_203]
[f 0 5 65278][f 2 1] 被压抑的阴影……[n]由@Emi_mi16 (twitter) / @emiumi (bsky)绘制[n][e]

[msg MSG_204]
[f 0 5 65278][f 2 1]会成为人类楷模吗？[n]由@cloudrifto (bsky/tumblr)绘制[n][e]

[msg MSG_205]
[f 0 5 65278][f 2 1]由匿名艺术家绘制[n][e]