[msg Item_010]
[s]Assault rifle manifested[n]from an awakened power.[n][e]

[msg Item_011]
[s]Model gun based on[n]a lever-action assault rifle.[n][e]

[msg Item_013]
[s]Model gun used regularly[n]by a famous, great man.[n][e]

[msg Item_015]
[s]Model gun based on[n]a lever-action assault rifle.[n][e]

[msg Item_016]
[s]Upgraded version of the[n]model gun Manipura.[n][e]

[msg Item_01B]
[s]Model gun crafted[n]using ancient techniques.[n][e]

[msg Item_01E]
[s]Upgraded version of the[n]model gun Sahasrara.[n][e]

[msg Item_0EA]
[s]Model gun with the[n]power of the root chakra[n]flowing through the barrel.[n][e]

[msg Item_0F0]
[s]Model gun that[n]shines bright.[n][e]

[msg Item_0F4]
[s]Model gun that fires[n]high-powered bullets using[n]the power of a chakra.[n][e]

[msg Item_0F6]
[s]Model gun used regularly[n]by a famous, great man.[n][e]

[msg Item_0F7]
[s]Model gun used regularly[n]by a famous, great man.[n][e]

[msg Item_0F8]
[s]Model gun with a[n]pattern that changes in[n]some rare instances.[n][e]

[msg Item_0FB]
[s]Model gun that is said to[n]bestow the blessings of[n]paradise upon its wielder.[n][e]

[msg Item_0FC]
[s]Model gun known to[n]unleash the utmost power.[n][e]