[msg Item_002]
[s]A rapier with a very[n]sharp tip.[n][e]

[msg Item_003]
[s]A thin, sharp blade[n]with a decorated hilt.[n][e]

[msg Item_004]
[s]A beautiful rapier with[n]an ethreal gleam.[n][e]

[msg Item_005]
[s]A rapier with an alluring[n]white shine.[n][e]

[msg Item_006]
[s]A rapier as light as[n]a feather.[n][e]

[msg Item_008]
[s]A thrusting sword for[n]novice duelists.[n][e]

[msg Item_00A]
[s]A rod that emits an[n]electric shock, stunning the victim.[n][e]

[msg Item_00B]
[s]A cursed rapier, dyed scarlet[n]with blood.[n][e]

[msg Item_00D]
[s]An old-looking sword that[n]emits a noise that sounds[n]like singing.[n][e]

[msg Item_00E]
[s]A thrusting sword that[n]can be used for fencing.[n][e]

[msg Item_010]
[s]An old-looking sword that[n]emits a noise that sounds[n]like singing.[n][e]

[msg Item_011]
[s]A rapier that once[n]belonged to a princess.[n][e]

[msg Item_013]
[s]A thrusting sword with[n]a sharper, narrower tip.[n][e]

[msg Item_014]
[s]A thrusting sword with a circular,[n]edgeless blade and a sharp tip.[n][e]

[msg Item_016]
[s]A foreign rapier whose[n]sting disturbs enemies.[n][e]

[msg Item_017]
[s]A thrusting sword that[n]can be used for fencing.[n][e]

[msg Item_019]
[s]A rapier that has been[n]sharpened to the utmost.[n][e]

[msg Item_01A]
[s]A compact thrusting sword[n]for swift, relentless attacks.[n][e]

[msg Item_01D]
[s]A compact thrusting sword[n]for swift, relentless attacks.[n][e]

[msg Item_01E]
[s]A sword forged in fire[n]that shines with intensity.[n][e]

[msg Item_023]
[s]An angelic rapier.[n][e]

[msg Item_0B4]
[s]Gloves that deal sound[n]barrierbreaking hits.[n][e]

[msg Item_0F5]
[s]A beautiful rapier of[n]gleaming silver.[n][e]

[msg Item_0FB]
[s]A weapon manifested[n]from an awakened power.[n][e]

[msg Item_0FE]
[s]A dagger used to drive[n]angels from Paradise.[n][e]

[msg Item_0FF]
[s]A noble dagger of a[n]fallen angel.[n][e]

[msg Item_100]
[s]A beautiful rapier that[n]glimmers like a starry night sky.[n][e]

[msg Item_101]
[s]A divine, angelic rapier.[n][e]

[msg Item_110]
[s]A rather long rapier[n]whose blade swirls in lightning.[n][e]

[msg Item_118]
[s]A dagger with a pale,[n]blue blade.[n][e]

[msg Item_119]
[s]A rapier that imbues[n]courage.[n][e]

[msg Item_121]
[s]A dagger best used for[n]parrying and defense.[n][e]

[msg Item_126]
[s]A dagger of judgment.[n][e]