[msg myth_170]
[s]Le vrai nom de[n]l'héroïne de Cendrillon.[n]On la surnomma[n]"Cendrillon" en moquerie[n]de ses habits poussiéreux[n]et couverts de suie.[n]Après avoir épousé[n]le prince, elle devint[n]la "Princesse Ella".[n][e]

[msg myth_200]
[s]Héroïne d'un conte[n]très célèbre,[n]l'histoire d'une souillon[n]maltraitée qui[n]se transforme en belle[n]princesse et séduit[n]un prince le temps[n]d'une soirée grâce[n]au pouvoir de[n]la magie.[n][e]

[msg myth_201]
[s]Héroïne d'un conte[n]très célèbre,[n]l'histoire d'une souillon[n]maltraitée qui[n]se transforme en belle[n]princesse et séduit[n]un prince le temps[n]d'une soirée grâce[n]au pouvoir de[n]la magie.[n][e]

[msg myth_211]
[s]Le vrai nom de[n]l'héroïne de Cendrillon.[n]On la surnomma[n]"Cendrillon" en moquerie[n]de ses habits poussiéreux[n]et couverts de suie.[n]Après avoir épousé[n]le prince, elle devint[n]la "Princesse Ella".[n][e]

[msg myth_363]
[s]Le vrai nom de Freyja,[n]une divinité Vanes de[n]la mythologie nordique.[n]Sœur jumelle de Freyr.[n]Son nom signifie "dís[n]des Vanes" (dís voulant[n]dire déesse). Sa beauté[n]est légendaire et[n]elle pratique la magie[n]comme une sorcière.[n][e]