[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54412 65535 0]Oui oui, baguette.[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s][f 0 8 2 1 2217]Tu ne devrais pas voir ça.[clr 27][e]
[s]Contacte le moddeur si tu arrive ici.[e]
[s]Clique sur un de ces choix pour de l'aide.[e]

[msg MSG_002_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54418 65535 0]Va sur Discord, ouvre un thread dans le[n]serveur Persona Modding, dans la chaîne[n]"P5 User Help".[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Suis les instructions, et tag Wisteria.[n]Si tu ne parle pas bien Anglais,[n]tu peux me tag aussi (Flastyy),[n]je traduirais la convo.[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54418 65535 0]Va sur Discord, ouvre un thread dans le[n]serveur Persona Modding, dans la chaîne[n]"P5 User Help".[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Suis les instructions, et tag Wisteria.[n]Si tu ne parle pas bien Anglais,[n]tu peux me tag aussi (Flastyy),[n]je traduirais la convo.[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54418 65535 0]Va sur Discord, ouvre un thread dans le[n]serveur Persona Modding, dans la chaîne[n]"P5 User Help".[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Suis les instructions, et tag Wisteria.[n]Si tu ne parle pas bien Anglais,[n]tu peux me tag aussi (Flastyy),[n]je traduirais la convo.[n][f 1 3 65535][w][e]

[msg MSG_004_5_0 [Jazz Club Manager]]
[s][vp 8 0 0 0 17 0]Merci pour votre attente.[n]Voilà votre commande.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 17 0]On a une performance spéciale aujourd'hui,[n]j'espère que vous allez l'aimer.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54458 65535 0]Ahh, ça fait du bien. Il n'y a rien de mieux[n]qu'une boisson fraîche et une musique relaxante.[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s][f 0 8 2 1 2217]Elle est une incroyable chanteuse.[clr 27][e]
[s]C'est vraiment bon![e]
[s]Santé![e]

[msg MSG_007_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Je comprends pourquoi ils appelent ça[n]une performance spéciale.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Haha, c'est bon à entendre.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][coop 9 5 9][vp 8 0 0 0 65535 0]Oui, à notre santé.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]Je suis content que l'on ait pu discuter[n]ici une fois de plus.[n][f 1 3 65535][w][e]

[sel SEL_010_0_0 top]
[s][f 0 8 2 1 2217]Parce qu'on s'entend bien.[clr 27][e]
[s][f 0 8 2 1 2217]Parce qu'on est similaire.[clr 27][e]

[msg MSG_011_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Je n'ai jamais partagé ma situation familiale[n]avec qui que ce soit avant.[n]Je me demande pourquoi je te l'ai racontée?[n][f 1 3 65535][w][e]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]C'est curieux, en effet.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]Nope, tu n'est pas sensé voir ce message.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]Ce message est un bug, go sur Discord.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Akechi]]
[s][bup 0 9 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 8040 65535 0]T'as fait ton installation à la rache ou bien?.[n]Ce message ne devrait pas apparaître.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][coop 9 5 9][vp 8 2 0 54417 65535 0]Maintenant que tu le mentionne,[n]peut-être bien qu'on est[n]similaire au fond...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Nous sommes tous deux victimes des adultes[n]qui ont injustement impactés nos vies.[n][f 1 3 65535][w][e]

[msg MSG_016_5_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ce message est un bug,[n]fais le nous savoir sur Discord.[n][f 1 3 65535][w][e]

[sel SEL_017_0_0 top]
[s][f 0 8 2 1 2217]Je pense que tu as raison.[clr 27][e]
[s]Je n'en suis pas sûre.[e]
[s]Tu vas finir ta boisson?[e]

[msg MSG_018_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][coop 9 10 9][vp 8 2 0 8020 65535 0]J'en suis encore plus sûr[n]après t'avoir parlé.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8020 65535 0]J'en suis encore plus sûr[n]après t'avoir rencontré.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][coop 9 5 9][vp 8 2 0 54418 65535 0]Tu fais vraiment les choses[n]à ton propre rythme, n'est-ce pas?[n]Je suppose que c'est l'une de nos différences.[n][f 1 3 65535][w][e]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 59 5 100][vp 8 0 0 0 65535 0]Mais peut-être que c'est simplement[n]la force de ne pas être préoccupé[n]par la perception des autres.[n]Dans ce cas... Je suis un peu envieux.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Akechi]]
[s][bup 0 9 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 8038 65535 0]Hmm... on a toujours pas fini nos boissons.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Voyons lequel de nous deux finit[n]son verre le plus vite.[n]Le premier qui finit a gagné.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Est-tu prête?[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Akechi]]
[s][vp 8 2 0 54414 65535 0]Bon, à la prochaine.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Tu ne devrais pas voir ce message,[n]il y a eu un bug.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Au fait, t'as vu le trailer pour P4R?[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54402 65535 0]T'as trouvé un bug.[n]En parlant de bug, tu savais que le doubleur[n]anglais d'Akechi a doublé[n]Spider-Man dans un cartoon?[n][f 1 3 65535][w][e]

[msg MSG_022_5_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Celui-ci aussi c'est un bug.[n]Si tu vois ce bug, go Discord.[n]C'est quand même fou que ce jeu[n]n'a jamais eu de doublage français, non?[n][f 1 3 65535][w][e]

[msg MND_023_0_0]
[s][vp 8 0 0 0 65535 0]J'ai l'impression que mon lien avec[n]Akechi devient de plus en plus profond...[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Détendons-nous et relaxons-nous.[n][f 1 3 65535][w][e]

[msg MND_025_0_0]
[s][vp 8 0 0 0 65535 0]J'ai apprécié ses talents de chanteuse[n]encore plus que la dernière fois...[f 1 3 65535][w][e]

[msg MSG_027_0_0 [Akechi]]
[s][vp 8 2 0 8053 65535 0]Bon, à la prochaine.[n][f 1 3 65535][w][e]

