[msg MSG_000_0_0 [Akechi]]
[f 2 1][f 4 6 0 9 1 65535 0][f 4 10 65535 0 0][f 3 1 8 2 0 54469 65535 0]L'atmosphère ici est merveilleuse...[n]Elle a un effet nostalgique,[n]tout comme la dernière fois.[n][f 1 3 65535][f 1 1][e]

[sel SEL_001_0_0 top]
[f 2 1]Si relaxant...[e]
[f 2 1]Cet endroit te va parfaitement.[e]
[f 2 1][f 0 8 2 1 2217]Nostalgique, huh?[f 0 1 27][e]

[msg MSG_002_0_0 [Akechi]]
[f 2 1][f 4 6 0 9 1 65535 0][f 4 10 65535 0 0][f 5 13 9 5 9][f 3 1 8 0 0 0 65535 0]Ça me rappelle des souvenirs.[n]J'ai passé beaucoup de temps ici[n]quand j'étais jeune.[n][f 1 3 65535][f 1 1][e]

[msg MSG_003_0_0 [Akechi]]
[f 2 1][f 4 6 0 9 1 65535 0][f 4 10 65535 0 0][f 5 13 9 5 9][f 3 1 8 0 0 0 65535 0]Oh, vraiment?[n]Je venais ici fréquemment[n]quand j'étais jeune.[n][f 1 3 65535][f 1 1][e]

[msg MSG_004_0_0 [Akechi]]
[f 2 1][f 4 6 0 9 1 65535 0][f 4 10 65535 0 0][f 5 13 9 10 9][f 3 1 8 0 0 0 65535 0]J'ai passé beaucoup de temps ici[n]quand j'étais jeune.[n][f 1 3 65535][f 1 1][e]

[msg MSG_005_0_0 [Akechi]]
[f 2 1][f 4 6 0 9 0 65535 0][f 4 10 65535 0 0][f 3 1 8 2 0 54450 65535 0]Bien sûr, ces jours-ci je suis le[n]Prince Détective, mais ma situation[n]familliale était... eh bien, compliquée.[n][f 1 3 65535][f 1 1][e]
[f 2 1][f 4 10 65535 0 0][f 3 1 8 0 0 0 65535 0]Le temps que je sois assez vieux[n]pour le réaliser, mon père était déjà parti.[n]Il ne me restait que ma mère.[n][f 1 3 65535][f 1 1][e]
[f 2 1][f 4 6 0 9 3 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 38 5 100][f 3 1 8 0 0 0 65535 0]Ma mère travaillait à[n]une boîte de nuit pas loin.[n]À chaque fois qu'elle devait ramener[n]un homme à la maison,[n]elle demandait à une connaissance ici[n]de me surveiller.[n][f 1 3 65535][f 1 1][e]
[f 2 1][f 4 6 0 9 3 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 38 5 100][f 3 1 8 0 0 0 65535 0]Il y avait toujours tellement de monde...[n]Je m'asseyais à une table et je siroter[n]un verre d'eau tout seul.[n][f 1 3 65535][f 1 1][e]
[f 2 1][f 4 6 0 9 3 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 38 5 100][f 3 1 8 0 0 0 65535 0]De temps en temps, ils venaient me voir pour[n]prendre de mes nouvelles, mais c'était peu fréquent.[n][f 1 3 65535][f 1 1][e]

[sel SEL_006_0_0 top]
[f 2 1]C'était horrible de sa part.[e]
[f 2 1][f 0 8 2 1 2217]...Tu as beaucoup souffert.[f 0 1 27][e]

[msg MSG_007_0_0 [Akechi]]
[f 2 1][f 4 6 0 9 0 65535 0][f 4 10 65535 0 0][f 3 1 8 0 0 0 65535 0]Ma mère a fait ce qu'elle avait à faire. C'était[n]clairement mieux que de rester à la maison.[n][f 1 3 65535][f 1 1][e]
[f 2 1][f 4 10 65535 0 0][f 3 1 8 0 0 0 65535 0]Elle a quitté les boulots de nuits[n]dès qu'elle a pû, et m'a élever en faisant[n]les boulots à mi-temps qu'elle trouvait.[n][f 1 3 65535][f 1 1][e]

[msg MSG_008_0_0 [Akechi]]
[f 2 1][f 4 6 0 9 3 65535 0][f 4 10 65535 0 0][f 4 1 8 2 0 8043 65535 0]Le fautif est mon père. Le piètre homme, inutile et dégénéré,[n]qui a abandonné ma mère.[n][f 1 3 65535][f 1 1][e]
[f 2 1][f 4 6 0 9 3 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 38 5 100][f 3 1 8 0 0 0 65535 0]Je voulais le forcer à enfin[n]s'excuser auprès d'elle. Mais...[n]ce n'est plus possible.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009_0_0 [Akechi]]
[f 2 1][f 4 6 0 9 0 65535 0][f 4 10 65535 0 0][f 5 13 9 5 9][f 3 1 8 0 0 0 65535 0]C'est du passé. Je n'ai aucune raison[n]non plus de rejetter la faute sur ma mère.[n][f 1 3 65535][f 1 1][e]

[msg MSG_009_5_0 [Akechi]]
[f 2 1][f 4 6 0 9 3 65535 0][f 4 10 65535 0 0][f 4 1 8 2 0 8043 65535 0]Le fautif est mon père. Le piètre homme, inutile et dégénéré,[n]qui a abandonné ma mère.[n][f 1 3 65535][f 1 1][e]
[f 2 1][f 4 6 0 9 3 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 38 5 100][f 3 1 8 0 0 0 65535 0]Je voulais le forcer à enfin[n]s'excuser auprès d'elle. Mais...[n]ce n'est plus possible.[n][f 1 3 65535][f 1 1][e]

[msg MSG_010_0_0 [Akechi]]
[f 2 1][f 4 6 0 9 1 65535 0][f 4 10 65535 0 0][f 3 1 8 2 0 54417 65535 0]Désolé. Je ne voulais pas que notre[n]conversation devienne si dépressive.[n][f 1 3 65535][f 1 1][e]
[f 2 1][f 4 6 0 9 0 65535 0][f 4 10 65535 0 0][f 3 1 8 0 0 0 65535 0]On devrait commander nos boissons.[n][f 1 3 65535][f 1 1][e]

[sel SEL_011_0_0 top]
[f 2 1]Je te laisse t'en charger.[e]
[f 2 1]Tout me va toujours.[e]
[f 2 1]Je vais prendre comme d'habitude![e]

[msg MSG_012_0_0 [Akechi]]
[f 2 1][f 4 6 0 9 1 65535 0][f 4 10 65535 0 0][f 5 13 9 5 9][f 3 1 8 2 0 54418 65535 0]Très bien, je vais passer commande.[n][f 1 3 65535][f 1 1][e]

[msg MSG_013_0_0 [Akechi]]
[f 2 1][f 4 6 0 9 1 65535 0][f 4 10 65535 0 0][f 5 13 9 5 9][f 3 1 8 2 0 8133 65535 0]Determinée à prouver que j'ai tords?[n][f 1 3 65535][f 1 1][e]
[f 2 1][f 4 6 0 9 1 65535 0][f 4 10 65535 0 0][f 3 1 8 0 0 0 65535 0]Très bien, testons cela.[n]Je vais commander au hasard.[n][f 1 3 65535][f 1 1][e]

[msg MSG_014_0_0 [Akechi]]
[f 2 1][f 4 6 0 9 0 65535 0][f 4 10 65535 0 0][f 5 13 9 10 9][f 3 1 8 2 0 8048 65535 0]Oh? Tu viens donc souvent ici?[n]Je suis heureux de l'entendre.[n][f 1 3 65535][f 1 1][e]
[f 2 1][f 4 6 0 9 0 65535 0][f 4 10 65535 0 0][f 3 1 8 0 0 0 65535 0]Je vais appeler le serveur, dans ce cas.[n][f 1 3 65535][f 1 1][e]

