[msg MND_080_0_0]
[s][vp 8 0 0 0 65535 0]Je devrais rentrer à la maison[n]avant d'attraper froid...[n][f 1 3 65535][w][e]

[msg MND_081_0_0]
[s][vp 8 0 0 0 65535 0]Ça serait sympa de rentrer à la maison...[n]mais je peux à peine bouger...[n][f 1 3 65535][w][e]

[msg MSG_000_0_0]
[s][vp 8 0 0 0 65535 0]Je me sens revigorée![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]...![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]J'ai aperçu ma réflection.[n]Ma peau a l'air plus douce![f 1 3 65535][w][e]

[msg MSG_002_0_0]
[s][vp 8 0 0 0 65535 0]...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Je suis étourdie...[n]Je crois que j'y suis allée trop fort...[n][f 1 3 65535][w][e]

[msg MSG_HOT_DAY]
[s][vp 8 0 0 0 65535 0]J'ai mis beaucoup d'effort[n]aujourd'hui...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0]
[s][vp 8 0 0 0 65535 0]Je me sens vraiment revigorée![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ces bains médicinaux[n]doivent être plutôt efficaces...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Je peux encore sentir l'arôme calmante...[n][f 1 3 65535][w][e]