[msg CHK_TOILET_MEN_01]
[s][vp 1 0 0 0 0 0]C'est les toilettes des filles...[n][w][e]
[s][vp 1 0 0 0 0 0]C'est bien plus sale[n]que celles du bâtiment des classes...[n][w][e]

[msg MSG_TOILET_WOMEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Tu ne sais pas que c'est[n]les toilettes des mecs?[n]T'es pas censée être ici...[n][w][e]

[msg MSG_TOILET_WOMEN]
[s][vp 1 0 0 0 0 0]Je n'ai aucune bonne raison d'être[n]dans les toilettes des garçons...[n][w][e]

[msg MND_E12310100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]C'est les toilettes des garçons...[n][w][e]
[s][vp 1 0 0 0 0 0]C'est bien plus sale[n]que celles du bâtiment des classes...[n][w][e]

[msg MND_E12720100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]C'est les toilettes des garçons...[n][w][e]
[s][vp 1 0 0 0 0 0]C'est bien plus sale[n]que celles du bâtiment des classes...[n][w][e]

[msg MND_E13710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]C'est les toilettes des garçons...[n][w][e]
[s][vp 1 0 0 0 0 0]There's nothing in particular[n]that I need to do here for now...[n][w][e]

[msg MND_E14130100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]C'est les toilettes des garçons...[n][w][e]
[s][vp 1 0 0 0 0 0]C'est bien plus sale[n]que celles du bâtiment des classes...[n][w][e]

[msg MND_COMMON_CHK_TOILET_ME]
[s][vp 1 0 0 0 0 0]C'est les toilettes des garçons...[n][w][e]
[s][vp 1 0 0 0 0 0]There's nothing in particular[n]that I need to do here for now...[n][w][e]

[msg MND_E12310100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]C'est les toilettes des garçons...[n][w][e]
[s][vp 1 0 0 0 0 0]I better get out of here.[n]Someone might get the wrong[n]idea if I stick around too long.[n][w][e]

[msg MND_E12720100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]C'est les toilettes des garçons...[n][w][e]
[s][vp 1 0 0 0 0 0]I better get out of here.[n]Someone might get the wrong[n]idea if I stick around too long.[n][w][e]

[msg MND_E13710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]C'est les toilettes des garçons...[n][w][e]
[s][vp 1 0 0 0 0 0]I better get out of here.[n]Someone might get the wrong[n]idea if I stick around too long.[n][w][e]

[msg MND_E14130100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]C'est les toilettes des garçons...[n][w][e]
[s][vp 1 0 0 0 0 0]I better get out of here.[n]Someone might get the wrong[n]idea if I stick around too long.[n][w][e]

[msg MND_COMMON_CHK_TOILET_WO]
[s][vp 1 0 0 0 0 0]C'est les toilettes des garçons...[n][w][e]
[s][vp 1 0 0 0 0 0]I better get out of here.[n]Someone might get the wrong[n]idea if I stick around too long.[n][w][e]