[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14]Vous êtes belles![n][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][f 5 14]Je suis heureuse que tu le pense.[n]On s'est mises d'accord de prendre[n]une photo de nos kimonos.[n][w][e]

[msg MSG_010_0_0 [Ann]]
[s][f 5 14]Peut-être qu'on fera une photo de groupe[n]la prochaine fois.[n][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][f 5 14]C'est une bonne photo à sa façon.[n]En effet, je crois que ça va nous inspirer de bons rêves.[n][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 5 14]Mais tu dois rêver de trucs spécifiques[n]si tu veux une bonne année, non?[n][w][e]


