[msg MSG_BTLSTART_001 [Cendrillon]]
[s][vp 8 0 2 1001 0 0]You'll be slaughtered at this rate![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_002 [Cendrillon]]
[s][vp 8 0 2 1002 0 0]Are you prepared for your debut?[n]The ball awaits...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_003 [Cendrillon]]
[s][vp 8 0 2 1003 0 0]Such tenacity...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_004 [Cendrillon]]
[s][vp 8 0 2 1004 0 0]Rend them to your heart's content![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_005 [Cendrillon]]
[s]Now, rend them! You shall tear the[n]desires of these swine apart![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_006 [Cendrillon]]
[s][vp 8 0 2 1006 0 0]Well, if those really are the shoes[n]you've chosen...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_007 [Cendrillon]]
[s][vp 8 0 2 1006 0 0]Well, if those really are the shoes[n]you've chosen...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_008 [Cendrillon]]
[s][vp 8 0 2 1007 0 0]Then we'll dance to the end.[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_009]
[s]In this form, I am the desire to destroy[n]incarnate-ho! You're not going to[n]le-hee-ave alive-ho![n][f 1 3 65535][w][e]

