[msg MSG_BTLSTART_002 [Cendrillon]]
[s][vp 8 0 2 1002 0 0]Sei pronta per il tuo debutto?[n]Lo show aspetta solo te...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_003 [Cendrillon]]
[s][vp 8 0 2 1003 0 0]Che tenacia...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_006 [Cendrillon]]
[s][vp 8 0 2 1006 0 0]Beh, se quelle sono le scarpe[n]che hai scelto...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_007 [Cendrillon]]
[s][vp 8 0 2 1006 0 0]Beh, se quelle sono le scarpe[n]che hai scelto...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_008 [Cendrillon]]
[s][vp 8 0 2 1007 0 0]Allora balleremo insieme fino alla fine.[n][f 1 3 65535][w][e]
