[msg Item_010]
[s]Un fucile d'assalto[n]manifestatosi da un potere risvegliato.[n][e]

[msg Item_011]
[s]Un modellino di un[n]fucile a leva.[n][e]

[msg Item_013]
[s]Modellino di un'arma spesso usata[n]da un grande uomo.[n][e]

[msg Item_015]
[s]Un modellino di un'arma basato[n]su fucile a leva.[n][e]

[msg Item_016]
[s]Versione migliorata della[n]Manipura.[n][e]

[msg Item_01B]
[s]Modellino di un'arma costruito[n]con antiche tecniche passate[n]di generazione in generazione.[n][e]

[msg Item_01E]
[s]Versione migliorata della[n]Sahasrara.[n][e]

[msg Item_0EA]
[s]Modellino di arma[n]con il potere del chakra[n]che scorre nella canna.[n][e]

[msg Item_0F0]
[s]Modelino di un'arma[n]che brilla intensamente.[n][e]

[msg Item_0F4]
[s]Modellino di un'arma che spara[n]proiettili perforanti usando[n]il potere di un chakra.[n][e]

[msg Item_0F6]
[s]Modellino di un'arma spesso usata[n]da un grande uomo.[n][e]

[msg Item_0F7]
[s]Modellino di un'arma spesso usata[n]da un grande uomo.[n][e]

[msg Item_0F8]
[s]Modellino di un'arma con[n]un pattern che cambia[n]in alcuni rari casi.[n][e]

[msg Item_0FB]
[s]Modellino di un'arma la cui[n]aura si dice confererisca la benedizione[n]del Paradiso a chi la usa.[n][e]

[msg Item_0FC]
[s]Modellino di un'arma conosciuta[n]per il suo potere assoluto.[n][e]