[msg myth_170]
[f 0 5 65278][f 2 1]Il vero nome[n]dell'eroina Cenerentola.[n]"Cinder Ella", dall'inglese,[n]era un soprannome[n]derisorio, datole perché[n]il duro lavoro la[n]lasciava coperta di polvere[n]e fuliggine. Dopo aver[n]sposato il suo principe,[n]divenne la "Principessa Ella".[n][e]

[msg myth_200]
[f 0 5 65278][f 2 1]Eroina del celeberrimo[n]racconto in cui una[n]bellissima orfanella[n]maltrattata, grazie a un[n]incantesimo, ottiene[n]uno splendido abito e[n]una carrozza fatata per[n]recarsi al ballo di un[n]principe.[n][e]

[msg myth_201]
[f 0 5 65278][f 2 1]Eroina del celeberrimo[n]racconto in cui una[n]bellissima orfanella[n]maltrattata, grazie a un[n]incantesimo, ottiene[n]uno splendido abito e[n]una carrozza fatata per[n]recarsi al ballo di un[n]principe.[n][e]

[msg myth_211]
[f 0 5 65278][f 2 1]Il vero nome[n]dell'eroina Cenerentola.[n]"Cinder Ella", dall'inglese,[n]era un soprannome[n]derisorio, datole perché[n]il duro lavoro la[n]lasciava coperta di polvere[n]e fuliggine. Dopo aver[n]sposato il suo principe,[n]divenne la "Principessa Ella".[n][e]

[msg myth_363]
[f 0 5 65278][f 2 1]Il vero nome di Freia,[n]divinità nordica[n]della stirpe dei Vani[n]e gemella minore[n]di Freyr.[n]Il suo nome significa[n]"dís dei Vani".[n]Nota per la sua[n]grande bellezza e per[n]la maestria nella magia.[n][e]