[msg Item_002]
[s]Un fioretto con una[n]punta molto affilata.[n][e]

[msg Item_003]
[s]Una lama sottile e affilata[n]con un impugnatura decorata.[n][e]

[msg Item_004]
[s]Un bellissimo fioretto che brilla[n]con un bagliore etereo.[n][e]

[msg Item_005]
[s]Un fioretto con un allettante[n]luccichio bianco.[n][e]

[msg Item_006]
[s]Un fioretto leggero[n]come una piuma.[n][e]

[msg Item_008]
[s]Una spada affilata per[n]combattenti dilettanti.[n][e]

[msg Item_00A]
[s]Una staffa che emette una[n]scarica elettrica sulla vittima, stordendola.[n][e]

[msg Item_00B]
[s]Un fioretto maledetto, dipinto di rosso[n]con il sangue.[n][e]

[msg Item_00D]
[s]Una vecchia spada che emette[n]un suono che assomiglia a[n]una dolce melodia.[n][e]

[msg Item_00E]
[s]Una spada affilata che[n]può essere usata per duellare.[n][e]

[msg Item_010]
[s]Una vecchia spada che emette[n]un suono che assomiglia a[n]una dolce melodia.[n][e]

[msg Item_011]
[s]Un fioretto che[n]apparteneva a una principessa.[n][e]

[msg Item_013]
[s]Una spada affilata[n]con una punta più sottile e affilata.[n][e]

[msg Item_014]
[s]Una spada affilata con una lama[n]circolare e smussata e[n]una punta molto afffilata.[n][e]

[msg Item_016]
[s]Uno strano fioretto il cui lieve [n]brusio disturba i nemici.[n][e]

[msg Item_017]
[s]Una spada affilata che[n]può essere usata per duellare.[n][e]

[msg Item_019]
[s]Un fioretto che[n]è stato affilato il più possibile.[n][e]

[msg Item_01A]
[s]Una spada compatta ma affilata,[n]perfetta per attacchi veloci e imprevedibili.[n][e]

[msg Item_01D]
[s]Una spada compatta ma affilata,[n]perfetta per attacchi veloci e imprevedibili.[n][e]

[msg Item_01E]
[s]Una spada forgiata nelle fiamme[n]che brilla intensamente.[n][e]

[msg Item_023]
[s]Un fioretto angelico.[n][e]

[msg Item_0B4]
[s]Guanti che colpiscono con una[n]forza capace di infrangere la[n]barriera del suono.[n][e]

[msg Item_0F5]
[s]Un bellissimo fioretto[n]fatto di pregiatissimo argento.[n][e]

[msg Item_0FB]
[s]Un'arma ottenuta[n]da un potere risvegliato.[n][e]

[msg Item_0FE]
[s]Una lama usata per cacciare[n]gli angeli dal Paradiso.[n][e]

[msg Item_0FF]
[s]Un nobile pugnale appartenuto[n]a un angelo ormai caduto.[n][e]

[msg Item_100]
[s]Un bellissimo fioretto che risplende[n]come un cielo stellato.[n][e]

[msg Item_101]
[s]Un fioretto divino.[n][e]

[msg Item_110]
[s]Un fioretto modificato e reso più lungo,[n]la cui lama si muove[n]in un turbinio di fulmini.[n][e]

[msg Item_118]
[s]Un pugnale con una pallida lama[n]di colore blu.[n][e]

[msg Item_119]
[s]Un fioretto che infonde coraggio[n]in chiunque lo usi.[n][e]

[msg Item_121]
[s]Una lama pensata principalmente[n]per parate e manovre difensive.[n][e]

[msg Item_126]
[s]La lama del giudizio.[n][e]