[msg msg_combine_PERSONA170 [Ella]]
[s]Io sono [clr 1][var 1][clr 27].[n][w][e]
[s]Tu affronteresti gli dei per proteggere la[n]giustizia in cui credi... Molto bene.[n]Allora balleremo fino alla fine.[n][w][e]

[msg msg_combine_PERSONA201 [Cendrillon]]
[s]Io sono [clr 1][var 1][clr 27].[n][w][e]
[s]Piuttosto che accettare una vita nelle ceneri, tu[n]lotteresti per la gloria? Allora lascia che io lanci un[n]incantesimo su di te...[n][w][e]

[msg msg_combine_PERSONA363 [Vanadis]]
[s]Io sono [clr 1][var 1][clr 27].[n][w][e]
[s]Lascia che virtù, bellezza e purezza di cuore ci alzino in alto le ali{0A}e ci lascino volare![n][w][e]

[msg msg_combine_PERSONA364 [Vanadis]]
[s]RESERVE[n][w][e]