[msg DVL_000_0_0 [Mysterious Voice]]
[s][vp 8 0 0 1 65535 0]Io sono te, e tu sei me...[n][f 1 2 160][w][e]

[msg DVL_002_0_0 [Cendrillon]]
[s][vp 8 0 0 3 65535 0]Piuttosto che accettare una vita[n]nelle ceneri...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 4 65535 0]Tu lotteresti per risplendere--[n]conosci i rischi.[n][f 1 3 65535][w][e]

[msg DVL_004_0_0 [Cendrillon]]
[s][vp 8 0 0 5 65535 0]Sei irremovibile...[n][f 1 3 65535][w][e]


