[msg DVL_001_0_0 [Cendrillon]]
[s][vp 8 0 0 0 6 0]Io sono [clr 1]Cendrillon[clr 27]-L'altra te che[n]esiste dentro di te...[n][f 1 3 65535][w][e]

[msg DVL_002_0_0 [Cendrillon]]
[s][vp 8 0 0 0 6 0]Anche se adesso dovessi scomparire,[n]sarò sempre al tuo fianco.[n][f 1 3 65535][w][e]

[msg DVL_003_0_0 [Cendrillon]]
[s][vp 8 0 0 0 6 0]Ci incontreremo ancora... quando il tuo destino[n]raggiunge la sua conclusione.[n][f 1 3 65535][w][e]
