[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54412 65535 0]Well then, why don't we get some[n]drinks?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s][f 0 8 2 1 2217]Any recommendations?[clr 27][e]
[s]Anything's fine by me.[e]
[s]An ice-cold beer for me.[e]

[msg MSG_002_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][coop 9 10 9][vp 8 0 0 0 65535 0]Nothing in particular, but if you don't[n]mind me choosing, then I'll put in a[n]random order.[n][f 1 3 65535][w][e]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]You don't have any soft drinks you[n]actively dislike, yes?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][coop 9 5 9][vp 8 0 0 0 65535 0]You know, I find the people who say[n]that end up being extremely picky,[n]in the end.[n][f 1 3 65535][w][e]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]Anyway, I'll put in an order. You don't[n]have any soft drinks you dislike, yes?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54418 65535 0]...You say that so deadpan, it almost[n]sounds like you're serious.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I'll pick some drinks, then, shall I?[n]There aren't any soft drinks you[n]actively dislike, right?[n][f 1 3 65535][w][e]

[msg MSG_004_5_0 [Jazz Club Manager]]
[s][vp 8 0 0 0 17 0]Thanks for waiting. Here's your order.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 17 0]We have a special performance today,[n]so I hope you enjoy it.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54458 65535 0]Ahh, that's nice. There's[n]nothing better than a cold[n]drink and some relaxing music.[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s][f 0 8 2 1 2217]Her singing is incredible.[clr 27][e]
[s]It really hit the spot![e]
[s]Cheers![e]

[msg MSG_007_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I see why they call it a special[n]performance.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Haha, that's good to hear.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]I'm glad we got to chat here again.[n][f 1 3 65535][w][e]

[sel SEL_010_0_0 top]
[s][f 0 8 2 1 2217]Because we get along.[clr 27][e]
[s][f 0 8 2 1 2217]Because we're similar.[clr 27][e]

[msg MSG_011_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I've never told anyone else about my[n]family situation. I wonder why[n]I told you? Curious indeed.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]A café, hm? Sounds like you have good[n]taste.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]Is that so? Now I'm intrigued... You[n]should show me the place sometime.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Akechi]]
[s][bup 0 9 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 8040 65535 0]You live there? I'm... not sure that counts[n]as a go-to place if you don't actually have[n]to go anywhere.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][coop 9 5 9][vp 8 2 0 54417 65535 0]Now that you mention it, maybe we are[n]pretty similar deep down...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]We're both victims of the adults who[n]unfairly impacted our lives.[n][f 1 3 65535][w][e]

[msg MSG_016_5_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]That reminds me, do you cook?[n][f 1 3 65535][w][e]

[sel SEL_017_0_0 top]
[s][f 0 8 2 1 2217]I think you're right.[clr 27][e]
[s]I don't know about that.[e]
[s]Gonna finish your drink?[e]

[msg MSG_018_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][coop 9 10 9][vp 8 2 0 8020 65535 0]I'm even more sure of that after having[n]talked with you.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8020 65535 0]I'm even more sure of that after having[n]met you.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][coop 9 5 9][vp 8 2 0 54418 65535 0]You really do things at your own pace,[n]don't you? I suppose that's one of our[n]differences.[n][f 1 3 65535][w][e]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 59 5 100][vp 8 0 0 0 65535 0]But perhaps that's simply the strength not[n]to be bothered by others' perceptions.[n]In which case... I'm a little envious.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Akechi]]
[s][bup 0 9 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 8038 65535 0]Hmm... we still haven't finished[n]our drinks.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Let's see who downs[n]theirs faster. First to finish wins.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Are you ready?[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Akechi]]
[s][vp 8 2 0 54414 65535 0]Well, see you later.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][coop 9 5 9][vp 8 0 0 0 65535 0]Yeah, cheers to us.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]I usually come here when I need some[n]time to really think on my own.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]So chatting with you here is really[n]quite refreshing.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54402 65535 0]You know, you're the first person I've[n]ever brought here...[n][f 1 3 65535][w][e]

[msg MSG_022_5_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]It's not like I was keeping it from anyone,[n]but... I suppose it goes to show we do[n]have some strange connection.[n][f 1 3 65535][w][e]

[msg MND_023_0_0]
[s][vp 8 0 0 0 65535 0]I feel like my bond with[n]Akechi is growing deeper...[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Let's sit back and relax.[n][f 1 3 65535][w][e]

[msg MND_025_0_0]
[s][vp 8 0 0 0 65535 0]I enjoyed her singing even[n]more than last time...[f 1 3 65535][w][e]

[msg MSG_027_0_0 [Akechi]]
[s][vp 8 2 0 8053 65535 0]Well, see you later.[n][f 1 3 65535][w][e]

