[msg MSG_000_0_0]
[s][vp 8 0 0 0 65535 0]Ci voleva un bel bagno.[n]Mi sento proprio rinfrescata![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]...![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ho intravisto il mio riflesso.[n]La mia pelle sembra molto più morbida![f 1 3 65535][w][e]

[msg MSG_002_0_0]
[s][vp 8 0 0 0 65535 0]...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Mi gira la testa…[n]credo proprio di aver esagerato…[n][f 1 3 65535][w][e]

[msg MSG_HOT_DAY]
[s][vp 8 0 0 0 65535 0]Forse ho esagerato un po' oggi…[n][f 1 3 65535][w][e]

[msg MSG_004_0_0]
[s][vp 8 0 0 0 65535 0]Mi sento come nuova![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Queste erbe medicinali devono[n]essere davvero efficaci…[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Riesco ancora a sentire gli aromi calmanti…[n][f 1 3 65535][w][e]

[msg MND_080_0_0]
[s][vp 8 0 0 0 65535 0]Dovrei andare a casa[n]prima di raffreddarmi troppo…[n][f 1 3 65535][w][e]

[msg MND_081_0_0]
[s][vp 8 0 0 0 65535 0]Sarebbe bello riuscire ad andare a casa…[n]Ma riesco a malapena a muovermi…[n][f 1 3 65535][w][e]