[msg MSG_000_0_0]
[s][vp 8 0 0 0 65535 0]I'm feeling refreshed![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]...![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]I caught a glimpse of my reflection.[n]My skin looks softer![f 1 3 65535][w][e]

[msg MSG_002_0_0]
[s][vp 8 0 0 0 65535 0]...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]I feel dizzy...[n]I think I overdid it...[n][f 1 3 65535][w][e]

[msg MSG_HOT_DAY]
[s][vp 8 0 0 0 65535 0]I pushed myself pretty hard[n]today...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0]
[s][vp 8 0 0 0 65535 0]I'm feeling really refreshed![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]These medicinal baths[n]must be quite effective...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]I can still smell the soothing aroma...[n][f 1 3 65535][w][e]

[msg MND_080_0_0]
[s][vp 8 0 0 0 65535 0]I should go home before[n]I get too cold...[n][f 1 3 65535][w][e]

[msg MND_081_0_0]
[s][vp 8 0 0 0 65535 0]It'd be nice to head home soon...[n]but I can barely move...[n][f 1 3 65535][w][e]