[msg CHK_TOILET_MEN_01]
[s][vp 1 0 0 0 0 0]This is the girls' bathroom...[n][w][e]
[s][vp 1 0 0 0 0 0]It's far dirtier than the ones[n]in the classroom building...[n][w][e]

[msg MSG_TOILET_WOMEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Don't you know that's the boys'[n]bathroom? You're not supposed[n]to be in there...[n][w][e]

[msg MSG_TOILET_WOMEN]
[s][vp 1 0 0 0 0 0]I don't have a good reason[n]to be in the boys' restroom...[n][w][e]

[msg MND_E12310100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]This is the ladies' bathroom...[n][w][e]
[s][vp 1 0 0 0 0 0]It's far dirtier than the ones[n]in the classroom building...[n][w][e]

[msg MND_E12720100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]This is the ladies' bathroom...[n][w][e]
[s][vp 1 0 0 0 0 0]It's far dirtier than the ones[n]in the classroom building...[n][w][e]

[msg MND_E13710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]This is the ladies' bathroom...[n][w][e]
[s][vp 1 0 0 0 0 0]There's nothing in particular[n]that I need to do here for now...[n][w][e]

[msg MND_E14130100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]This is the ladies' bathroom...[n][w][e]
[s][vp 1 0 0 0 0 0]It's far dirtier than the ones[n]in the classroom building...[n][w][e]

[msg MND_COMMON_CHK_TOILET_ME]
[s][vp 1 0 0 0 0 0]This is the ladies' bathroom...[n][w][e]
[s][vp 1 0 0 0 0 0]There's nothing in particular[n]that I need to do here for now...[n][w][e]

[msg MND_E12310100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]This is the boys' bathroom...[n][w][e]
[s][vp 1 0 0 0 0 0]I better get out of here.[n]Someone might get the wrong[n]idea if I stick around too long.[n][w][e]

[msg MND_E12720100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]This is the boys' bathroom...[n][w][e]
[s][vp 1 0 0 0 0 0]I better get out of here.[n]Someone might get the wrong[n]idea if I stick around too long.[n][w][e]

[msg MND_E13710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]This is the boys' bathroom...[n][w][e]
[s][vp 1 0 0 0 0 0]I better get out of here.[n]Someone might get the wrong[n]idea if I stick around too long.[n][w][e]

[msg MND_E14130100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]This is the boys' bathroom...[n][w][e]
[s][vp 1 0 0 0 0 0]I better get out of here.[n]Someone might get the wrong[n]idea if I stick around too long.[n][w][e]

[msg MND_COMMON_CHK_TOILET_WO]
[s][vp 1 0 0 0 0 0]This is the boys' bathroom...[n][w][e]
[s][vp 1 0 0 0 0 0]I better get out of here.[n]Someone might get the wrong[n]idea if I stick around too long.[n][w][e]