[msg CHK_TOILET_MEN_01]
[s][vp 1 0 0 0 0 0]Questo è il bagno delle femmine…[n][w][e]
[s][vp 1 0 0 0 0 0]È molto più sporco dei bagni[n]della scuola…[n][w][e]

[msg MSG_TOILET_WOMEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Non lo sai che quello è il[n]bagno maschile?[n]Non dovresti entrarci…[n][w][e]

[msg MSG_TOILET_WOMEN]
[s][vp 1 0 0 0 0 0]Non ho motivo di entrare[n]nel bagno dei maschi…[n][w][e]

[msg MND_E12310100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Questo è il bagno delle femmine…[n][w][e]
[s][vp 1 0 0 0 0 0]È molto più sporco dei bagni[n]della scuola…[n][w][e]

[msg MND_E12720100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Questo è il bagno delle femmine…[n][w][e]
[s][vp 1 0 0 0 0 0]È molto più sporco dei bagni[n]della scuola…[n][w][e]

[msg MND_E13710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Questo è il bagno delle femmine…[n][w][e]
[s][vp 1 0 0 0 0 0]There's nothing in particular[n]that I need to do here for now...[n][w][e]

[msg MND_E14130100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Questo è il bagno dei maschi…[n][w][e]
[s][vp 1 0 0 0 0 0]È molto più sporco dei bagni[n]della scuola…[n][w][e]

[msg MND_COMMON_CHK_TOILET_ME]
[s][vp 1 0 0 0 0 0]Questo è il bagno delle femmine…[n][w][e]
[s][vp 1 0 0 0 0 0]There's nothing in particular[n]that I need to do here for now...[n][w][e]

[msg MND_E12310100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Questo è il bagno dei maschi…[n][w][e]
[s][vp 1 0 0 0 0 0]Farei meglio a uscire di qui.[n]Qualcuno potrebbe farsi delle[n]idee sbagliate se rimango qui troppo a lungo…[n][w][e]

[msg MND_E12720100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Questo è il bagno dei maschi…[n][w][e]
[s][vp 1 0 0 0 0 0]Farei meglio a uscire di qui.[n]Qualcuno potrebbe farsi delle[n]idee sbagliate se rimango qui troppo a lungo…[n][w][e]

[msg MND_E13710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Questo è il bagno dei maschi…[n][w][e]
[s][vp 1 0 0 0 0 0]Farei meglio a uscire di qui.[n]Qualcuno potrebbe farsi delle[n]idee sbagliate se rimango qui troppo a lungo…[n][w][e]

[msg MND_E14130100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Questo è il bagno dei maschi…[n][w][e]
[s][vp 1 0 0 0 0 0]Farei meglio a uscire di qui.[n]Qualcuno potrebbe farsi delle[n]idee sbagliate se rimango qui troppo a lungo…[n][w][e]

[msg MND_COMMON_CHK_TOILET_WO]
[s][vp 1 0 0 0 0 0]Questo è il bagno dei maschi…[n][w][e]
[s][vp 1 0 0 0 0 0]Farei meglio a uscire di qui.[n]Qualcuno potrebbe farsi delle[n]idee sbagliate se rimango qui troppo a lungo…[n][w][e]