[msg MSG_TOILET_WOMEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Don't you know that's the boys'[n]bathroom? You're not supposed[n]to be in there...[n][w][e]

[msg MSG_TOILET_WOMEN]
[s][vp 1 0 0 0 0 0]I don't have a good reason[n]to be in the boys' restroom...[n][w][e]

[msg MND_E12010100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]This seems to be the[n]boys' restroom for the[n]upper-class students.[n][w][e]
[s][vp 1 0 0 0 0 0]I can hear the voices[n]of boys chatting inside...[n][w][e]

[msg MND_E12310100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]I don't have a good reason[n]to be in the boys' restroom...[n][w][e]

[msg MND_E12720100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]I don't have a good reason[n]to be in the boys' restroom...[n][w][e]

[msg MND_E13710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]I don't have a good reason[n]to be in the boys' restroom...[n][w][e]

[msg MND_E14130100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]I don't have a good reason[n]to be in the boys' restroom...[n][w][e]

[msg MND_COMMON_CHK_TOILET_WO]
[s][vp 1 0 0 0 0 0]I don't have a good reason[n]to be in the boys' restroom...[n][w][e]

[msg MSG_E13710100_CHK_TOILET_5 [Ryuji]]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 2 1 7114 65535 0]Whoa, wait! You can't be goin' in there![n]Let's hurry and get to your classroom![n][w][e]