[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14]Mica male![n][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][f 5 14]Sono contenta di sentirlo. Ci siamo messe d'accordo[n]per fare una foto tutte insieme.[n][w][e]

[msg MSG_010_0_0 [Ann]]
[s][f 5 14]La prossima volta potremmo fare[n]una foto di gruppo.[n][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][f 5 14]È una bella foto, a modo suo.[n]In effetti, credo che ti aiuterà[n]a fare dei bei sogni, Ryuji.[n][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 5 14]Però se vuoi avere un anno positivo[n]devi sognare delle cose specifiche,[n]dico bene?[n][w][e]


