[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14]Lookin' good![n][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][f 5 14]I'm glad you think so. We all agreed to take a[n]picture of our kimonos.[n][w][e]

[msg MSG_010_0_0 [Ann]]
[s][f 5 14]Maybe we'll do a group shot next time.[n][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][f 5 14]This photo is good in its own way.[n]Indeed, I believe it will inspire[n]some good dreams.[n][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 5 14]But you gotta dream of specific[n]things if you want to have a good[n]year, right?[n][w][e]


