[msg MSG_BTLSTART_002 [Cendrillon]]
[s][vp 8 0 2 1002 0 0]Bist du bereit für deinen Auftritt?[n]Der Ball wartet...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_003 [Cendrillon]]
[s][vp 8 0 2 1003 0 0]Solch hartnäckigkeit...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_006 [Cendrillon]]
[s][vp 8 0 2 1006 0 0]Tja, wenn du dich wirklich[n]für diese Schuhe entschieden hast...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_007 [Cendrillon]]
[s][vp 8 0 2 1006 0 0]Tja, wenn du dich wirklich[n]für diese Schuhe entschieden hast...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_008 [Cendrillon]]
[s][vp 8 0 2 1007 0 0]Dann lass uns bis zum Ende tanzen.[n][f 1 3 65535][w][e]
