[msg Item_010]
[s]Sturmgeweher manifestiert[n]aus einer erweckten Kraft.[n][e]

[msg Item_011]
[s]Modell-Waffe welche auf[n]einem Sturmgeweher basiert.[n][e]

[msg Item_013]
[s]Eine Modell-Waffe welche von[n]einem berühmten Mann genutzt wurde.[n][e]

[msg Item_015]
[s]Modell-Waffe welche auf[n]einem Sturmgeweher basiert.[n][e]

[msg Item_016]
[s]Eine erweiterte Version[n]der Modell-Waffe Manipura.[n][e]

[msg Item_01B]
[s]Modell-Waffe welche mit[n]alten Techniken hergestellt wurde.[n][e]

[msg Item_01E]
[s]Eine erweiterte Version[n]der Modell-Waffe Sahasrara.[n][e]

[msg Item_0EA]
[s]Modell-Waffe durch welche die[n]Kraft des Chakra fließt.[n][e]

[msg Item_0F0]
[s]Modell-Waffe die[n]hell leuchtet.[n][e]

[msg Item_0F4]
[s]Modell-Waffe welche[n]starke Kugeln durch[n]die Power des Chakra feuert.[n][e]

[msg Item_0F6]
[s]Eine Modell-Waffe welche von[n]einem berühmten Mann genutzt wurde.[n][e]

[msg Item_0F7]
[s]Eine Modell-Waffe welche von[n]einem berühmten Mann genutzt wurde.[n][e]

[msg Item_0F8]
[s]Model-Waffe, welche[n]in seltenen Fällen[n]das Muster wechselt.[n][e]

[msg Item_0FB]
[s]Modell-Waffe welche angeblich[n]den Segen des Himmels[n]auf den Nutzer überträgt.[n][e]

[msg Item_0FC]
[s]Modell-Waffe welche[n]unendliche Macht entfesselt.[n][e]