[msg myth_170]
[f 0 5 65278][f 2 1]The true name of[n]Cinderella's heroine.[n]"Cinder Ella" was a[n]derisive nickname,[n]born from her hard[n]work always leaving[n]her dusty and sooty.[n]After marrying her[n]prince, she became[n]"Princess Ella."[n][e]

[msg myth_200]
[f 0 5 65278][f 2 1]The French name of[n]the titular heroine of[n]Cinderella, an oft-[n]retold tale of great[n]renown in which a[n]mistreated waif gains[n]luxury, beauty, and[n]a single night's dance[n]with a prince through[n]the power of magic.[n][e]

[msg myth_201]
[f 0 5 65278][f 2 1]The French name of[n]the titular heroine of[n]Cinderella, an oft-[n]retold tale of great[n]renown in which a[n]mistreated waif gains[n]luxury, beauty, and[n]a single night's dance[n]with a prince through[n]the power of magic.[n][e]

[msg myth_211]
[f 0 5 65278][f 2 1]The true name of[n]Cinderella's heroine.[n]"Cinder Ella" was a[n]derisive nickname,[n]born from her hard[n]work always leaving[n]her dusty and sooty.[n]After marrying her[n]prince, she became[n]"Princess Ella."[n][e]

[msg myth_363]
[f 0 5 65278][f 2 1]The true name of[n]Freyja, of the Norse[n]Vanir deities. Younger[n]twin sister of Freyr.[n]Her name means "ds[n]of the Vanir"—ds[n]being a goddess.[n]Known to be a great[n]beauty and a witchlike[n]master of magic.[n][e]