[msg myth_170]
[f 0 5 65278][f 2 1][s]Der wahre Name von[n]Cinderella/Aschen-[n]puttel. „Cinder“ ist[n]Englisch für „Asche“.[n]Den Beinamen erhielt[n]sie, weil sie durch die[n]Arbeit stets schmutzig[n]war. Nach der Hochzeit[n]mit dem Prinzen wurde[n]sie „Prinzessin Ella“.[n][e][n][e]

[msg myth_200]
[f 0 5 65278][f 2 1][s]Der französische Name[n]von Aschenputtel,[n]dem beliebten Märchen,[n]in dem eine gepeinigte[n]Magd durch Magie zu[n]Luxus, Schönheit[n]und einem Tanz mit[n]einem Prinzen[n]gelangt.[n][e][n][e]

[msg myth_201]
[f 0 5 65278][f 2 1][s]Der französische Name[n]von Aschenputtel,[n]dem beliebten Märchen,[n]in dem eine gepeinigte[n]Magd durch Magie zu[n]Luxus, Schönheit[n]und einem Tanz mit[n]einem Prinzen[n]gelangt.[n][e][n][e]

[msg myth_211]
[f 0 5 65278][f 2 1][s]Der wahre Name von[n]Cinderella/Aschen-[n]puttel. „Cinder“ ist[n]Englisch für „Asche“.[n]Den Beinamen erhielt[n]sie, weil sie durch die[n]Arbeit stets schmutzig[n]war. Nach der Hochzeit[n]mit dem Prinzen wurde[n]sie „Prinzessin Ella“.[n][e][n][e]

[msg myth_363]
[f 0 5 65278][f 2 1]Der echte Name der[n]nordischen Vanir-Göttin[n]Freyja, der jüngeren[n]Zwillingsschwester von[n]Frery. Ihr Name[n]bedeutet „Göttin der[n]Vanir“. Bekannt als[n]große Schönheit[n]und hexengleiche[n]Meisterin der Magie.[n][e]