[msg Item_002]
[s]Ein Rapier mit einer[n]sehr scharfen Spitze.[n][e]

[msg Item_003]
[s]Eine dünne, scharfe Klinge[n]mit dekoriertem Griff.[n][e]

[msg Item_004]
[s]Ein wunderschöner Rapier[n]mit himlischem Glanz.[n][e]

[msg Item_005]
[s]Ein Rapier mit hinreißendem[n]weißen Glanz.[n][e]

[msg Item_006]
[s]Ein Rapier, so[n]leicht wie eine Feder.[n][e]

[msg Item_008]
[s]Ein Stoßschwert für[n]Duell-Neulinge.[n][e]

[msg Item_00A]
[s]Eine Stange welche einen[n]elektrischen Schlag abgibt,[n]um das Opfer zu beteuben.[n][e]

[msg Item_00B]
[s]Ein verfluchter Rapier,[n]blutrot gefärbt.[n][e]

[msg Item_00D]
[s]Ein altmodisches Schwert[n]welches ein Geräusch wie[n]Gesang abgibt.[n][e]

[msg Item_00E]
[s]Ein Stoßschwert welches[n]fürs Fechten genutzt werden kann.[n][e]

[msg Item_010]
[s]Ein altmodisches Schwert[n]welches ein Geräusch wie[n]Gesang abgibt.[n][e]

[msg Item_011]
[s]Ein Rapier, welcher[n] einst einer Prinzessin gehörte.[n][e]

[msg Item_013]
[s]Ein Stoßschwert mit einer[n]schärferen, dünneren Klinge.[n][e]

[msg Item_014]
[s]Ein Stoßschwert mit einer runden,[n]kantenlosen Klinge und einer scharfen Spitze.[n][e]

[msg Item_016]
[s]Ein ausländisches Rapier,[n]dessen Stachel Feinde stört.[n][e]

[msg Item_017]
[s]Ein Stoßschwert welches[n]fürs Fechten genutzt werden kann.[n][e]

[msg Item_019]
[s]Ein Rapier welches,[n]zur Perfektion geschärft wurde.[n][e]

[msg Item_01A]
[s]Ein kompaktes Stoßschwert[n]für schnelle, unerbittliche Angriffe.[n][e]

[msg Item_01D]
[s]Ein kompaktes Stoßschwert[n]für schnelle, unerbittliche Angriffe.[n][e]

[msg Item_01E]
[s]Ein Schwert in Feuer geschmiedet,[n]welches mit Intensität leuchtet.[n][e]

[msg Item_023]
[s]Ein himmlischer Rapier.[n][e]

[msg Item_0B4]
[s]Handschuhe, die Schall[n]durchbrechende Schläge verursachen.[n][e]

[msg Item_0F5]
[s]Ein wunderschöner Rapier[n]aus glitzerndem silber.[n][e]

[msg Item_0FB]
[s]Eine Waffe manifestiert[n]aus einer erweckten Kraft.[n][e]

[msg Item_0FE]
[s]Ein Dolch, geschaffen um[n]Engel aus dem Himmel zu treiben.[n][e]

[msg Item_0FF]
[s]Der noble Dolch eines[n]Gefallenen Engels.[n][e]

[msg Item_100]
[s]Ein wunderschöner Rapier[n]welcher wie ein Sternenhimmel leuchtet.[n][e]

[msg Item_101]
[s]Ein göttlicher, himmlischer Rapier.[n][e]

[msg Item_110]
[s]Ein etwas langer Rapier,[n]dessen Klinge von Blitzen umschlungen wird.[n][e]

[msg Item_118]
[s]Ein Dolch mit einer blasen,[n]blauen Klinge.[n][e]

[msg Item_119]
[s]Ein Rapier welcher,[n]Mut erfüllt.[n][e]

[msg Item_121]
[s]Ein Dolch der am besten für[n]die defensive genutzt wird.[n][e]

[msg Item_126]
[s]Ein Dolch der Verurteilung.[n][e]