[msg msg_combine_PERSONA170 [Ella]]
[s]Ich bin [clr 1][var 1][clr 27].[n][w][e]
[s]Du würdest Götter töten, um die[n]Gerechtigkeit an die du glaubst zu schützen...na gut.[n]Dann lass uns bis zum Ende tanzen.[n][w][e]

[msg msg_combine_PERSONA201 [Cendrillon]]
[s]Ich bin [clr 1][var 1][clr 27].[n][w][e]
[s]Statt dich einem Leben in Flamen zu opfern[n]würdest du nach Glanz streben? Dann lass mich meine[n]Magie an dir wirken...[n][w][e]

[msg msg_combine_PERSONA363 [Vanadis]]
[s]Ich bin [clr 1][var 1][clr 27].[n][w][e]
[s]Lass Reinheit, Schönheit und Tugend[n]unsere Flügel{0A}spreizen und lass uns Fliegen![n][w][e]

[msg msg_combine_PERSONA364 [Vanadis]]
[s]RESERVE[n][w][e]