[msg DVL_000_0_0 [Mysterious Voice]]
[s][vp 8 0 0 1 65535 0]Ich bin du, du bist ich...[n][f 1 2 160][w][e]

[msg DVL_002_0_0 [Cendrillon]]
[s][vp 8 0 0 3 65535 0]Statt ein Leben in[n]Glut zu akzeptieren...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 4 65535 0]Strebst du nach Glanz--[n]du kennst das Risiko.[n][f 1 3 65535][w][e]

[msg DVL_004_0_0 [Cendrillon]]
[s][vp 8 0 0 5 65535 0]So unnachgiebig...[n][f 1 3 65535][w][e]


