[msg DVL_001_0_0 [Cendrillon]]
[s][vp 8 0 0 0 6 0]Ich bin [clr 1]Cendrillon[clr 27]—das andere du[n]welches in dir existiert...[n][f 1 3 65535][w][e]

[msg DVL_002_0_0 [Cendrillon]]
[s][vp 8 0 0 0 6 0]Auch wenn ich in diesem Moment verschwinde,[n]werde ich immer an deiner Seite stehen.[n][f 1 3 65535][w][e]

[msg DVL_003_0_0 [Cendrillon]]
[s][vp 8 0 0 0 6 0]Wir werden uns wiedersehen...[n]sollte dein Schicksal sein Ende finden.[n][f 1 3 65535][w][e]
