[msg MSG_004_5_0 [Jazz Club Manager]]
[s][vp 8 0 0 0 17 0]Danke für's warten. Hier ist eure Bestellung.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 17 0]Wir haben heute Abend eine spezielle Vorstellung,[n]ich hoffe sie gefällt euch.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54458 65535 0]Ahh, das ist super. Es gibt[n]nichts besseres als ein kaltes[n]Getränk und entspannende Musik.[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s][f 0 8 2 1 2217]Ihre Stimme ist unglaublich.[clr 27][e]
[s]Das hat echt gut getan![e]
[s]Prost![e]

[msg MSG_007_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ich verstehe, warum sie es eine[n]spezielle Vorstellung nennen.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Haha, freut mich zu hören.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][coop 9 5 9][vp 8 0 0 0 65535 0]Ja, zu unserem Wohl.[n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]Ich bin froh das wir hier wieder sprechen konnten.[n][f 1 3 65535][w][e]

[sel SEL_010_0_0 top]
[s][f 0 8 2 1 2217]Weil wir uns gut verstehen.[clr 27][e]
[s][f 0 8 2 1 2217]Weil wir uns ähnlich sind.[clr 27][e]

[msg MSG_011_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ich habe auch noch niemandem so viel über[n]meine Familie erzählt. Warum gerade dir?[n]Sehr interessant.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][coop 9 5 9][vp 8 2 0 54417 65535 0]Jetzt, wo du es erwähnst... Vielleicht[n]sind wir uns ja doch ähnlicher,[n]als gedacht...[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Wir wurden beide Opfer von Erwachsenen,[n]die unsere Leben auf unfaire Weise[n]beeinflusst haben.[n][f 1 3 65535][w][e]

[sel SEL_017_0_0 top]
[s][f 0 8 2 1 2217]Ich glaube, du hast recht.[clr 27][e]
[s]Ich weiß ja nicht.[e]
[s]Trinkst du das leer?[e]

[msg MSG_018_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][coop 9 10 9][vp 8 2 0 8020 65535 0]Nach unserer Unterhaltung bin ich mir[n]dessen sogar noch sicherer als zuvor.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8020 65535 0]Seitdem wir uns getroffen haben, bin ich mir[n]dessen sogar noch sicherer als zuvor.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][coop 9 5 9][vp 8 2 0 54418 65535 0]Du machst Dinge wirklich nach deinem[n]eigenem Tempo, oder?[n][f 1 3 65535][w][e]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 59 5 100][vp 8 0 0 0 65535 0]Das ist wohl ein Aspekt[n]in dem wir uns unterscheiden.[n][f 1 3 65535][w][e]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 59 5 100][vp 8 0 0 0 65535 0]Aber vielleicht besitzt du einfach die Stärke,[n]dich nicht von den Meinungen anderer stören zu lassen.[n][f 1 3 65535][w][e]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 59 5 100][vp 8 0 0 0 65535 0]Und ich muss gestehen...ich bin etwas neidisch.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Akechi]]
[s][bup 0 9 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 8038 65535 0]Hmm... wir haben unsere Gläser[n]noch nicht leer getrunken.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Mal sehen, wer schneller[n]trinkt. Wer zuerst fertig ist, gewinnt.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Bist du soweit?[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Akechi]]
[s][vp 8 2 0 54414 65535 0]Na dann, bis zum nächsten mal.[n][f 1 3 65535][w][e]

[msg MND_023_0_0]
[s][vp 8 0 0 0 65535 0]Meine Bindung zu Akechi[n]vertieft sich...[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]...Lehnen wir uns zurück und genießen es.[n][f 1 3 65535][w][e]

[msg MND_025_0_0]
[s][vp 8 0 0 0 65535 0]Mir hat ihr Gesang noch besser[n]gefallen als Letztes mal...[f 1 3 65535][w][e]

[msg MSG_027_0_0 [Akechi]]
[s][vp 8 2 0 8053 65535 0]Na dann, bis zum nächsten mal.[n][f 1 3 65535][w][e]

