[msg MSG_000_0_0]
[s][vp 8 0 0 0 65535 0]Ich fühle mich erfrischt![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]...![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ich habe mein Spiegelbild gesehen.[n]Meine Haut sieht zarter aus![n][f 1 3 65535][w][e]

[msg MSG_002_0_0]
[s][vp 8 0 0 0 65535 0]...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Mir ist schwindlig...[n]Ich glaube ich hab es übertrieben...[n][f 1 3 65535][w][e]

[msg MSG_HOT_DAY]
[s][vp 8 0 0 0 65535 0]Ich habe mich heute zu sehr[n]strapaziert...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0]
[s][vp 8 0 0 0 65535 0]Ich fühle mich so erfrischt![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Diese medizinischen Bäder[n]sind wohl sehr effektiv...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Ich rieche immer noch[n]das beruhigende Aroma.[n][f 1 3 65535][w][e]

[msg MND_080_0_0]
[s][vp 8 0 0 0 65535 0]Ich sollte heimgehen bevor[n]mir zu kalt wird...[n][f 1 3 65535][w][e]

[msg MND_081_0_0]
[s][vp 8 0 0 0 65535 0]Es wäre schön bald zuhause zu sein...[n]doch ich kann mich kaum bewegen...[n][f 1 3 65535][w][e]

