[msg MSG_TOILET_WOMEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Das ist doch das Jungs Klo,[n]oder? Da drin hast du nichts[n]verloren...[n][w][e]

[msg MSG_TOILET_WOMEN]
[s][vp 1 0 0 0 0 0]Ich habe keinen guten Grund[n]auf die Jungs Toilette zu gehen...[n][w][e]

[msg MND_E12010100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Ich habe keinen guten Grund[n]auf die Jungs Toilette zu gehen...[n][w][e]

[msg MND_E12310100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Ich habe keinen guten Grund[n]auf die Jungs Toilette zu gehen...[n][w][e]

[msg MND_E12720100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Ich habe keinen guten Grund[n]auf die Jungs Toilette zu gehen...[n][w][e]

[msg MND_E13710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Ich habe keinen guten Grund[n]auf die Jungs Toilette zu gehen...[n][w][e]

[msg MND_E14130100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Ich habe keinen guten Grund[n]auf die Jungs Toilette zu gehen...[n][w][e]

[msg MND_COMMON_CHK_TOILET_WO]
[s][vp 1 0 0 0 0 0]Ich habe keinen guten Grund[n]auf die Jungs Toilette zu gehen...[n][w][e]

[msg MSG_E13710100_CHK_TOILET_5 [Ryuji]]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 2 1 7114 65535 0]Whoa, wait! You can't be goin' in there![n]Let's hurry and get to your classroom![n][w][e]