[msg CHK_TOILET_MEN_01]
[s][vp 1 0 0 0 0 0]Das ist die Mädchen Toilette...[n][w][e]
[s][vp 1 0 0 0 0 0]Es ist viel schmutziger als die[n]im Klassenzimmergebäude...[n][w][e]

[msg MSG_TOILET_WOMEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]Das ist doch das Jungs Klo,[n]oder? Da drin hast du nichts[n]verloren...[n][w][e]

[msg MSG_TOILET_WOMEN]
[s][vp 1 0 0 0 0 0]I don't have a good reason[n]to be in the boys' restroom...[n][w][e]

[msg MND_E12310100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Das ist die Toilette für die Jungs...[n][w][e]
[s][vp 1 0 0 0 0 0]Es ist viel schmutziger als die[n]im Klassenzimmergebäude...[n][w][e]

[msg MND_E12720100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Das ist die Toilette für die Jungs...[n][w][e]
[s][vp 1 0 0 0 0 0]Es ist viel schmutziger als die[n]im Klassenzimmergebäude...[n][w][e]

[msg MND_E13710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Das ist die Toilette für die Jungs...[n][w][e]
[s][vp 1 0 0 0 0 0]There's nothing in particular[n]that I need to do here for now...[n][w][e]

[msg MND_E14130100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Das ist die Toilette für die Jungs...[n][w][e]
[s][vp 1 0 0 0 0 0]Es ist viel schmutziger als die[n]im Klassenzimmergebäude...[n][w][e]

[msg MND_COMMON_CHK_TOILET_ME]
[s][vp 1 0 0 0 0 0]Das ist die Toilette für die Jungs...[n][w][e]
[s][vp 1 0 0 0 0 0]Es gibt hier im Moment nichts[n]Besonderes, was ich tun muss..[n][w][e]

[msg MND_E12310100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Das ist die Toilette für die Jungs...[n][w][e]
[s][vp 1 0 0 0 0 0]Ich verschwinde wohl besser.[n]Jemand kriegt noch falsche Ideen[n]wenn ich mich länger hier herumtreibe.[n][w][e]

[msg MND_E12720100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Das ist die Toilette für die Jungs...[n][w][e]
[s][vp 1 0 0 0 0 0]Ich verschwinde wohl besser.[n]Jemand kriegt noch falsche Ideen[n]wenn ich mich länger hier herumtreibe.[n][w][e]

[msg MND_E13710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Das ist die Toilette für die Jungs...[n][w][e]
[s][vp 1 0 0 0 0 0]Ich verschwinde wohl besser.[n]Jemand kriegt noch falsche Ideen[n]wenn ich mich länger hier herumtreibe.[n][w][e]

[msg MND_E14130100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Das ist die Toilette für die Jungs...[n][w][e]
[s][vp 1 0 0 0 0 0]Ich verschwinde wohl besser.[n]Jemand kriegt noch falsche Ideen[n]wenn ich mich länger hier herumtreibe.[n][w][e]

[msg MND_COMMON_CHK_TOILET_WO]
[s][vp 1 0 0 0 0 0]Das ist die Toilette für die Jungs...[n][w][e]
[s][vp 1 0 0 0 0 0]Ich verschwinde wohl besser.[n]Jemand kriegt noch falsche Ideen[n]wenn ich mich länger hier herumtreibe.[n][w][e]