[msg MSG_199]
[f 0 5 65278][f 2 1]MSG_199[n][e]

[msg MSG_200]
[f 0 5 65278][f 2 1]MSG_200[n][e]

[msg MSG_201]
[f 0 5 65278][f 2 1]With style and grace![n]The keyart for Kasumi as Protagonist.[n]Drawn by @trillmunch[n][e]

[msg MSG_202]
[f 0 5 65278][f 2 1]An icon illustration for[n]Kasumi as Protagonist.[n]Drawn by @trillmunch[n][e]

[msg MSG_203]
[f 0 5 65278][f 2 1]A repressed shadow...[n]By @Emi_mi16 (twitter) / @emiumi (bsky)[n][e]

[msg MSG_204]
[f 0 5 65278][f 2 1]Will you become humanity's paragon?[n]By @cloudrifto (bsky/tumblr)