[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14]Sieht gut aus![n][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][f 5 14]Freut mich, dass du auch so denkst. Wir wollten[n]zusammen ein Bild in unseren Kimonos.[n][w][e]

[msg MSG_010_0_0 [Ann]]
[s][f 5 14]Nächstes mal sollten wir ein Gruppenfoto machen.[n][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][f 5 14]Das Foto ist auf seine Weise auch gut.[n]Ich glaube, es wird gute[n]Träume inspirieren.[n][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 5 14]Aber man muss von etwas Bestimmtem[n]träumen, wenn man ein gutes Jahr[n]haben will, oder?[n][w][e]


