[msg msg_combine_PERSONA170 [엘라]]
[s]나는 [clr 1][var 1][clr 27].[n][w][e]
[s]자신의 신념을 위해 신조차 거역하는구나...[n]그럼 무대의 막이 내릴 때까지 함께 춤춰줄게.[n][w][e]

[msg msg_combine_PERSONA201 [상드리용]]
[s]나는 [clr 1][var 1][clr 27].[n][w][e]
[s]재투성이로 있기보단 한때의 영화를 원하니?[n]그렇다면 마법을 걸어줄게...[n][w][e]

[msg msg_combine_PERSONA363 [상드리용]]
[s]저는 [clr 1][var 1][clr 27].[n][w][e]
[s]깨끗하게, 바르게, 아름답게, 함께 춤춰 보아요...![n][w][e]

[msg msg_combine_PERSONA364 [상드리용]]
[s]RESERVE[n][w][e]