[msg msg_combine_PERSONA170 [엘라]]
[s]나는 [clr 1][var 1][clr 27]야.[n][w][e]
[s]네가 믿는 정의를 지키기 위해 신마저 쓰러뜨리려 한다니... 좋아.[n]그렇다면 끝까지 함께 춤추자.[n][w][e]

[msg msg_combine_PERSONA201 [상드리용]]
[s]나는 [clr 1][var 1][clr 27]야.[n][w][e]
[s]재 속의 삶을 받아들이기보다,[n]영광을 위해 나아가겠다는 거지? 그럼 내가 너에게[n]마법을 걸어줄게...[n][w][e]

[msg msg_combine_PERSONA363 [바나디스]]
[s]나는 [clr 1][var 1][clr 27]야.[n][w][e]
[s]순수와 덕, 아름다움이 우리의 날개를 들어 올려{0A}함께 날아오르자![n][w][e]

[msg msg_combine_PERSONA364 [바나디스]]
[s]RESERVE[n][w][e]