[msg MSG_199]
[f 0 5 65278][f 2 1]199[n][e]

[msg MSG_200]
[f 0 5 65278][f 2 1]200[n][e]

[msg MSG_201]
[f 0 5 65278][f 2 1]스타일과 우아함을 겸비한 모습![n]주인공으로서의 카스미 키 아트입니다.[n]그림: @trillmunch[n][e]

[msg MSG_202]
[f 0 5 65278][f 2 1]주인공으로서의[n]카스미 아이콘 일러스트입니다.[n]그림: @trillmunch[n][e]

[msg MSG_203]
[f 0 5 65278][f 2 1]억눌린 그림자...[n]작성자: @Emi_mi16 (twitter) / @emiumi (bsky)[n][e]

[msg MSG_204]
[f 0 5 65278][f 2 1]당신은 인류의 모범이 될 수 있을까요?[n]작성자: @cloudrifto (bsky/tumblr)