[msg Item_010]
[s]力の覚醒と共に顕現した銃[n]突撃銃の形状をしている[n][e]

[msg Item_011]
[s]大口径タイプの[n]モデルガン[n][e]

[msg Item_013]
[s]古びた大口径の[n]モデルガン[n][e]

[msg Item_015]
[s]マフィア映画でよく見る[n]モデルガン[n][e]

[msg Item_016]
[s]破壊神皇を強化した[n]銃型の鋳物[n][e]

[msg Item_01B]
[s]特殊部隊も愛用する[n]モデルガン[n][e]

[msg Item_01E]
[s]サハスラーラを強化した[n]銃型の鋳物[n][e]

[msg Item_0EA]
[s]天国産とも言われる[n]モデルガン[n][e]

[msg Item_0F0]
[s]終わりの時へと誘う[n]モデルガン[n][e]

[msg Item_0F4]
[s]破壊の神の姿を現した[n]銃型の鋳物[n][e]

[msg Item_0F6]
[s]全米人気NO.1の[n]モデルガン[n][e]

[msg Item_0F7]
[s]高い威力をもつ[n]モデルガン[n][e]

[msg Item_0F8]
[s]HELKLO銃口が真っ赤に燃焼する[n]モデルガン[n][e]

[msg Item_0FB]
[s]凍るほどの恐怖を与える[n]モデルガン[n][e]

[msg Item_0FC]
[s]魔王の魔力を銃身に宿した[n]銃型の鋳物[n][e]