[msg msg_combine_PERSONA170 [エラ]]
[s]私は [clr 1][var 1][clr 27].[n][w][e]
[s]正しき信念を貫くためならば、[n]j神殺しも厭いません。[n]さあ、最後まで踊りましょう[n][w][e]

[msg msg_combine_PERSONA201 [サンドリヨン]]
[s]私は [clr 1][var 1][clr 27].[n][w][e]
[s]灰をかぶったままよりも…[n]仮初の栄華を求める。[n]そういうことだね?[n][w][e]

[msg msg_combine_PERSONA363 [ヴァナディース]]
[s]私は [clr 1][var 1][clr 27].[n][w][e]
[s]あまねく争いを[n]愛と豊穣で包み込みましょう。[n][w][e]

[msg msg_combine_PERSONA364 [ヴァナディース]]
[s]RESERVE[n][w][e]