[msg MSG_TOILET_WOMEN_MORU [モルガナ]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]おい、そっちは男子トイレだぞ。[n]女子トイレは隣だ。[n][w][e]

[msg MSG_TOILET_WOMEN]
[s][vp 1 0 0 0 0 0]男子トイレに入る理由はありません。[n][w][e]

[msg MND_E12310100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]男子トイレに入る理由はありません。[n][w][e]

[msg MND_E12720100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]男子トイレに入る理由はありません。[n][w][e]

[msg MND_E13710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]男子トイレに入る理由はありません。[n][w][e]

[msg MND_E14130100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]男子トイレに入る理由はありません。[n][w][e]

[msg MND_COMMON_CHK_TOILET_WO]
[s][vp 1 0 0 0 0 0]男子トイレに入る理由はありません。[n][w][e]

[msg MSG_E13710100_CHK_TOILET_5 [坂本 竜司]]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 2 1 7114 65535 0]おい待て待て!そんなとこに入るな![n]ほら、さっさと教室いくぞ![n][w][e]