[msg MSG_BTLSTART_002 [Cendrillon]]
[s][vp 8 0 2 1002 0 0]¿Todo listo para el estreno?[n]¡Te están esperando para el baile![n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_003 [Cendrillon]]
[s][vp 8 0 2 1003 0 0]Cuánta tenacidad...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_006 [Cendrillon]]
[s][vp 8 0 2 1006 0 0]Si esos son los zapatos[n]que decides llevar...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_007 [Cendrillon]]
[s][vp 8 0 2 1006 0 0]Si esos son los zapatos[n]que decides llevar...[n][f 1 3 65535][w][e]

[msg MSG_BTLSTART_008 [Cendrillon]]
[s][vp 8 0 2 1007 0 0]Bailaremos hasta el final.[n][f 1 3 65535][w][e]
