[msg Item_010]
[s]Ametralladora que surgió[n]del despertar de un poder.[n][e]

[msg Item_011]
[s]Réplica basada en un rifle de asalto.[n][e]

[msg Item_013]
[s]Réplica que usaba con frecuencia[n]un famoso hombre ilustre.[n][e]

[msg Item_015]
[s]Réplica basada en un rifle de asalto.[n][e]

[msg Item_016]
[s]Versión mejorada de la réplica Manipura.[n][e]

[msg Item_01B]
[s]Réplica elaborada con[n]antiguas técnicas artesanales.[n][e]

[msg Item_01E]
[s]Versión mejorada de[n]la réplica Sahasrara.[n][e]

[msg Item_0EA]
[s]Réplica con el poder del chakra raíz[n]fluyendo por su cañón.[n][e]

[msg Item_0F0]
[s]Réplica que emite[n]una luz brillante.[n][e]

[msg Item_0F4]
[s]Réplica que dispara balas de gran[n]potencia gracias al poder de un chakra.[n][e]

[msg Item_0F6]
[s]Réplica que usaba con frecuencia[n]un famoso hombre ilustre.[n][e]

[msg Item_0F7]
[s]Réplica que usaba con frecuencia[n]un famoso hombre ilustre.[n][e]

[msg Item_0F8]
[s]Réplica con un diseño que[n]cambia de vez en cuando.[n][e]

[msg Item_0FB]
[s]Réplica que otorga la gracia[n]del paraíso a quien la empuña.[n][e]

[msg Item_0FC]
[s]Réplica conocida por[n]desatar un poder supremo.[n][e]