[msg myth_170]
[f 0 5 65278][f 2 1]El nombre verdadero de[n]la heroína de la historia[n]de Cenicienta. “Cenicienta”[n]era un apodo burlón[n]nacido de que siempre[n]acababa cubierta de[n]ceniza por su duro[n]trabajo. Al casarse[n]con el príncipe, se[n]convirtió en la[n]“Princesa Ella”.[n][e]

[msg myth_200]
[f 0 5 65278][f 2 1]Nombre francés de la[n]heroína titular de[n]Cenicienta, un cuento[n]muy popular que se ha[n]recontado muchas veces.[n]Una joven maltratada[n]consigue belleza, lujo[n]y un baile con un[n]príncipe gracias al[n]poder de la magia.[n][e]

[msg myth_201]
[f 0 5 65278][f 2 1]Nombre francés de la[n]heroína titular de[n]Cenicienta, un cuento[n]muy popular que se ha[n]recontado muchas veces.[n]Una joven maltratada[n]consigue belleza, lujo[n]y un baile con un[n]príncipe gracias al[n]poder de la magia.[n][e]

[msg myth_211]
[f 0 5 65278][f 2 1]El nombre verdadero de[n]la heroína de la historia[n]de Cenicienta. “Cenicienta”[n]era un apodo burlón[n]nacido de que siempre[n]acababa cubierta de[n]ceniza por su duro[n]trabajo. Al casarse[n]con el príncipe, se[n]convirtió en la[n]“Princesa Ella”.[n][e]

[msg myth_363]
[f 0 5 65278][f 2 1]El nombre verdadero de[n]Freyja, diosa del clan[n]Vanir en la mitología[n]nórdica. Hermana gemela[n]menor de Freyr. Su[n]nombre significa “diosa[n]de los Vanir”. Es[n]conocida por su gran[n]belleza y por dominar[n]la magia como una bruja.[n][e]