[msg Item_002]
[s]Un sable con una hoja[n]muy fina.[n][e]

[msg Item_003]
[s]Un sable fino y afilado[n]con una empuñadura decorada.[n][e]

[msg Item_004]
[s]Un bello sable con un[n]brillo etéreo.[n][e]

[msg Item_005]
[s]Un sable con un atractivo[n]brillo blanco.[n][e]

[msg Item_006]
[s]Un sable ligero como una pluma.[n][e]

[msg Item_008]
[s]Un sable de estocada para[n]duelistas novatos.[n][e]

[msg Item_00A]
[s]Un bastón que electrocuta y[n]aturde al enemigo.[n][e]

[msg Item_00B]
[s]Un sable maldito, teñido de escarlata[n]con sangre.[n][e]

[msg Item_00D]
[s]Una espada antigua que emite[n]un sonido parecido a un canto.[n][e]

[msg Item_00E]
[s]Un sable de estocada[n]que puede usarse para esgrima.[n][e]

[msg Item_010]
[s]Una espada antigua que emite[n]un sonido parecido a un canto.[n][e]

[msg Item_011]
[s]Un sable que perteneció[n]a una princesa.[n][e]

[msg Item_013]
[s]Un sable de estocada con una[n]punta estrecha y afilada.[n][e]

[msg Item_014]
[s]Un sable de estocada con una hoja circular y una punta afilada.[n][e]

[msg Item_016]
[s]Un sable que perturba a[n]los enemigos.[n][e]

[msg Item_017]
[s]Un sable de estocada[n]que puede usarse para esgrima.[n][e]

[msg Item_019]
[s]Un sable afilado hasta el extremo.[n][e]

[msg Item_01A]
[s]Un sable compacto para[n]ataques rápidos e implacables.[n][e]

[msg Item_01D]
[s]Un sable compacto para[n]ataques rápidos e implacables.[n][e]

[msg Item_01E]
[s]Una espada forjada en fuego[n]que brilla con intensidad.[n][e]

[msg Item_023]
[s]Un sable angelical.[n][e]

[msg Item_0B4]
[s]Guantes que asestan[n]impactos fuertes.[n][e]

[msg Item_0F5]
[s]Un bello sable de plata reluciente.[n][e]

[msg Item_0FB]
[s]Un arma que surgió[n]del despertar de un poder.[n][e]

[msg Item_0FE]
[s]Una daga usada para desterrar[n]a los ángeles del paraíso.[n][e]

[msg Item_0FF]
[s]La noble daga[n]de un ángel caído.[n][e]

[msg Item_100]
[s]Un bello sable que brilla[n]como un cielo estrellado.[n][e]

[msg Item_101]
[s]Un sable divino y angelical.[n][e]

[msg Item_110]
[s]Un sable largo con una hoja[n]envuelta en rayos.[n][e]

[msg Item_118]
[s]Una daga con un filo[n]de color azul claro.[n][e]

[msg Item_119]
[s]Un sable que infunde valor.[n][e]

[msg Item_121]
[s]Una daga que viene bien[n]para bloquear y para defenderse.[n][e]

[msg Item_126]
[s]Una daga del juicio.[n][e]