[msg msg_combine_PERSONA170 [Ella]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Matarías a dioses para proteger[n]la justicia en la que crees...[n]Muy bien, bailaremos hasta el final.[n][w][e]

[msg msg_combine_PERSONA201 [Cendrillon]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]En lugar de protegerte entre cenizas,[n]¿te atreves a buscar la gloria? Entonces deja[n]que mi conjuro recaiga sobre ti...[n][w][e]

[msg msg_combine_PERSONA363 [Vanadis]]
[s]Soy [clr 1][var 1][clr 27].[n][w][e]
[s]Que la pureza, la virtud y la belleza eleven nuestras alas...{0A}¡y alcemos vuelo![n][w][e]

[msg msg_combine_PERSONA364 [Vanadis]]
[s]RESERVE[n][w][e]