[msg DVL_000_0_0 [Voz misteriosa]]
[s][vp 8 0 0 1 65535 0]Yo soy tú, tú eres yo...[n][f 1 2 160][w][e]

[msg DVL_002_0_0 [Cendrillon]]
[s][vp 8 0 0 3 65535 0]En lugar de protegerte[n]entre cenizas...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 4 65535 0]Tu objetivo es la gloria, así que[n]ya sabes a lo que te arriesgas.[n][f 1 3 65535][w][e]

[msg DVL_004_0_0 [Cendrillon]]
[s][vp 8 0 0 5 65535 0]Que cabezota.[n][f 1 3 65535][w][e]


