[msg DVL_001_0_0 [Cendrillon]]
[s][vp 8 0 0 0 6 0]Soy [clr 1]Cendrillon[clr 27],el otro yo[n]que habita en tu interior.[n][f 1 3 65535][w][e]

[msg DVL_002_0_0 [Cendrillon]]
[s][vp 8 0 0 0 6 0]Aunque desaparezca ahora,[n]siempre estaré a tu lado.[n][f 1 3 65535][w][e]

[msg DVL_003_0_0 [Cendrillon]]
[s][vp 8 0 0 0 6 0]Volveremos a encontrarnos... cuando tu destino[n]llegue a su fin.[n][f 1 3 65535][w][e]
