[msg MSG_000_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54412 65535 0]¿Y bien? ¿Pedimos algo de beber?[n][f 1 3 65535][w][e]

[sel SEL_001_0_0 top]
[s][f 0 8 2 1 2217]¿Qué recomiendas?[clr 27][e]
[s]Me gusta todo.[e]
[s]Pídeme una cerveza bien fría.[e]

[msg MSG_002_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][coop 9 10 9][vp 8 0 0 0 65535 0]Nada en particular, pero si no[n]te importa que elija, escogeré[n]algo al azar.[n][f 1 3 65535][w][e]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]Te gustan todos los refrescos, ¿no?[n][f 1 3 65535][w][e]

[msg MSG_003_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][coop 9 5 9][vp 8 0 0 0 65535 0]¿Sabes? La mayoría de gente[n]que dice eso acaba siendo[n]muy quisquillosa.[n][f 1 3 65535][w][e]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0][f 4 24 0 4 0 36 5 100]Voy a pedir algo. Te gustan[n]todos los refrescos, ¿no?[n][f 1 3 65535][w][e]

[msg MSG_004_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54418 65535 0]Lo dices de forma tan inexpresiva[n]que parece que vayas en serio.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Iré a por algo de beber. ¿Hay algún[n]refresco que no te guste?[n][f 1 3 65535][w][e]

[msg MSG_004_5_0 [Gerente del club de jazz]]
[s][vp 8 0 0 0 17 0]Gracias por la espera.[n]Aquí tenéis las bebidas.[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 17 0]Hoy tenemos una actuación especial,[n]esperamos que la disfrutéis.[n][f 1 3 65535][w][e]

[msg MSG_005_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 54458 65535 0]Ahhh... Qué bien sienta. No hay[n]nada mejor que una bebida fría[n]y algo de música relajante.[n][f 1 3 65535][w][e]

[sel SEL_006_0_0 top]
[s][f 0 8 2 1 2217]Canta de maravilla.[clr 27][e]
[s]¡Justo lo que necesitaba![e]
[s]¡Salud![e]

[msg MSG_007_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ya veo por qué lo llaman una[n]actuación especial.[n][f 1 3 65535][w][e]

[msg MSG_008_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Jaja, me alegra oírlo.[n][f 1 3 65535][w][e]

[msg MSG_032_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][coop 9 5 9][vp 8 0 0 0 65535 0]¡Salud![n][f 1 3 65535][w][e]

[msg MSG_009_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8127 65535 0]Me alegra que hayamos podido charlar aquí[n]otra vez.[n][f 1 3 65535][w][e]

[sel SEL_010_0_0 top]
[s][f 0 8 2 1 2217]Porque nos llevamos bien.[clr 27][e]
[s][f 0 8 2 1 2217]Porque nos parecemos.[clr 27][e]

[msg MSG_011_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Jamás había hablado con[n]nadie sobre mi familia. ¿Por qué te[n]lo he contado? Qué curioso.[n][f 1 3 65535][w][e]

[msg MSG_012_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]¿Una cafetería, eh? Parece que tienes[n]buen gusto.[n][f 1 3 65535][w][e]

[msg MSG_013_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 2 0 8133 65535 0]¿Ah, sí? Interesante...[n]Deberías invitarme algún día.[n][f 1 3 65535][w][e]

[msg MSG_014_0_0 [Akechi]]
[s][bup 0 9 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 8040 65535 0]¿Vives allí? Hm... no estoy seguro[n]de que cuente[n]si ni siquiera tienes[n]que moverte.[n][f 1 3 65535][w][e]

[msg MSG_015_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][coop 9 5 9][vp 8 2 0 54417 65535 0]Ahora que lo dices, es posible que[n]seamos parecidos en el fondo.[n][f 1 3 65535][w][e]

[msg MSG_016_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Ambos somos víctimas de adultos[n]injustos que nos han marcado[n]de por vida.[n][f 1 3 65535][w][e]

[msg MSG_016_5_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Por cierto, ¿sabes cocinar?[n][f 1 3 65535][w][e]

[sel SEL_017_0_0 top]
[s][f 0 8 2 1 2217]Creo que tienes razón.[clr 27][e]
[s]No lo tengo claro.[e]
[s]¿Te vas a acabar tu bebida?[e]

[msg MSG_018_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][coop 9 10 9][vp 8 2 0 8020 65535 0]Y después de hablar contigo,[n]es algo que tengo más claro[n]que nunca.[n][f 1 3 65535][w][e]

[msg MSG_019_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 8020 65535 0]Ahora que te conozco, es algo[n]que tengo más claro que nunca.[n][f 1 3 65535][w][e]

[msg MSG_020_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][coop 9 5 9][vp 8 2 0 54418 65535 0]Vas a tu ritmo... Supongo que[n]es una de nuestras diferencias.[n][f 1 3 65535][w][e]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][f 4 24 0 4 0 59 5 100][vp 8 0 0 0 65535 0]Será porque te da igual[n]lo que los demás piensen de ti,[n]lo cual es envidiable.[n][f 1 3 65535][w][e]

[msg MSG_029_0_0 [Akechi]]
[s][bup 0 9 4 65535 0][f 4 10 65535 0 0][vp 8 2 0 8038 65535 0]Hm... Aún no hemos terminado[n]nuestras bebidas.[n][f 1 3 65535][w][e]

[msg MSG_030_0_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Veamos quien se la acaba más rápido.[n]El primero en terminar gana.[n][n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]¿Estás lista?[n][f 1 3 65535][w][e]

[msg MSG_031_0_0 [Akechi]]
[s][vp 8 2 0 54414 65535 0]Bueno, nos vemos.[n][f 1 3 65535][w][e]

[msg MSG_021_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Suelo venir aquí cuando necesito[n]estar a solas y pensar.[n][f 1 3 65535][w][e]
[s][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Así que hablar con alguien aquí[n]es nuevo para mí.[n][f 1 3 65535][w][e]

[msg MSG_022_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 2 0 54402 65535 0]Nunca había traído a nadie aquí...[n][f 1 3 65535][w][e]

[msg MSG_022_5_0 [Akechi]]
[s][bup 0 9 1 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]No es que lo estuviese ocultando,[n]pero... demuestra que tenemos[n]alguna clase de conexión.[n][f 1 3 65535][w][e]

[msg MND_023_0_0]
[s][vp 8 0 0 0 65535 0]Siento que mi vínculo[n]con Akechi se está fortaleciendo.[n][f 1 3 65535][w][e]

[msg MSG_024_0_0 [Akechi]]
[s][bup 0 9 0 65535 0][f 4 10 65535 0 0][vp 8 0 0 0 65535 0]Toca relajarse...[n][f 1 3 65535][w][e]

[msg MND_025_0_0]
[s][vp 8 0 0 0 65535 0]La música estuvo aún mejor que la última vez...[f 1 3 65535][w][e]

[msg MSG_027_0_0 [Akechi]]
[s][vp 8 2 0 8053 65535 0]Bueno, nos vemos.[n][f 1 3 65535][w][e]

