[msg MSG_000_0_0]
[s][vp 8 0 0 0 65535 0]¡Me siento como nueva![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]¡...![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]He visto mi reflejo...[n]¡Mi piel se ve más suave![f 1 3 65535][w][e]

[msg MSG_002_0_0]
[s][vp 8 0 0 0 65535 0]...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Me siento un poco mareada...[n]Creo que me he pasado...[n][f 1 3 65535][w][e]

[msg MSG_HOT_DAY]
[s][vp 8 0 0 0 65535 0]Hoy me he pasado un poco...[n][f 1 3 65535][w][e]

[msg MSG_004_0_0]
[s][vp 8 0 0 0 65535 0]¡Me siento como nueva![n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Estos baños medicinales deben[n]de ser muy efectivos...[n][f 1 3 65535][w][e]
[s][vp 8 0 0 0 65535 0]Todavía siento el aroma relajante...[n][f 1 3 65535][w][e]

[msg MND_080_0_0]
[s][vp 8 0 0 0 65535 0]Será mejor que me vaya a casa[n]antes de que coja frío...[n][f 1 3 65535][w][e]

[msg MND_081_0_0]
[s][vp 8 0 0 0 65535 0]Debería volver a casa...[n]pero casi no puedo moverme...[n][f 1 3 65535][w][e]

