[msg MSG_TOILET_WOMEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]¡Oye, que ese es el baño[n]de los chicos! Ahí no pintas nada.[n][w][e]

[msg MSG_TOILET_WOMEN]
[s][vp 1 0 0 0 0 0]No tengo ningún motivo[n]para ir al baño de los chicos.[n][w][e]

[msg MND_E12310100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]No tengo ningún motivo[n]para ir al baño de los chicos.[n][w][e]

[msg MND_E12720100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]No tengo ningún motivo[n]para ir al baño de los chicos.[n][w][e]

[msg MSG_E13710100_CHK_TOILET_5 [Ryuji]]
[s][bup 0 2 202 65535 0][f 4 10 65535 0 0][vp 8 2 1 7114 65535 0]Joder, tía. ¡No puedes entrar ahí![n]¡Date prisa y vamos a tu clase![n][w][e]

[msg MND_E13710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]No tengo ningún motivo[n]para ir al baño de los chicos.[n][w][e]

[msg MND_E14130100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]No tengo ningún motivo[n]para ir al baño de los chicos.[n][w][e]

[msg MND_COMMON_CHK_TOILET_WO]
[s][vp 1 0 0 0 0 0]No tengo ningún motivo[n]para ir al baño de los chicos.[n][w][e]