[msg CHK_TOILET_MEN_01]
[s][vp 1 0 0 0 0 0]Este es el baño de las chicas.[n][w][e]
[s][vp 1 0 0 0 0 0]Está mucho más sucio[n]que los que hay cerca de las aulas.[n][w][e]

[msg MSG_TOILET_WOMEN_MORU [Morgana]]
[s][bup 0 3 0 0 0][f 4 10 65535 0 0][vp 8 2 1 1167 65535 0]¡Oye, que ese es el baño[n]de los chicos! Ahí no pintas nada.[n][w][e]

[msg MSG_TOILET_WOMEN]
[s][vp 1 0 0 0 0 0]No tengo ningún motivo[n]para ir al baño de los chicos.[n][w][e]

[msg MND_E12310100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Este es el baño de los chicos.[n][w][e]
[s][vp 1 0 0 0 0 0]Está mucho más sucio[n]que los que hay cerca de las aulas.[n][w][e]

[msg MND_E12720100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Este es el baño de los chicos.[n][w][e]
[s][vp 1 0 0 0 0 0]Está mucho más sucio[n]que los que hay cerca de las aulas.[n][w][e]

[msg MND_E13710100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Este es el baño de los chicos.[n][w][e]
[s][vp 1 0 0 0 0 0]No tengo nada que hacer[n]aquí por ahora...[n][w][e]

[msg MND_E14130100_CHK_TOILET]
[s][vp 1 0 0 0 0 0]Este es el baño de los chicos.[n][w][e]
[s][vp 1 0 0 0 0 0]Está mucho más sucio[n]que los que hay cerca de las aulas.[n][w][e]

[msg MND_COMMON_CHK_TOILET_ME]
[s][vp 1 0 0 0 0 0]Este es el baño de los chicos.[n][w][e]
[s][vp 1 0 0 0 0 0]No tengo nada que hacer[n]aquí por ahora...[n][w][e]

[msg MND_E12310100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Este es el baño de los chicos.[n][w][e]
[s][vp 1 0 0 0 0 0]Será mejor que me vaya. Alguien[n]podría hacerse una idea equivocada[n]si me quedo mucho rato.[n][w][e]

[msg MND_E12720100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Este es el baño de los chicos.[n][w][e]
[s][vp 1 0 0 0 0 0]Será mejor que me vaya. Alguien[n]podría hacerse una idea equivocada[n]si me quedo mucho rato.[n][w][e]

[msg MND_E13710100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Este es el baño de los chicos.[n][w][e]
[s][vp 1 0 0 0 0 0]Será mejor que me vaya. Alguien[n]podría hacerse una idea equivocada[n]si me quedo mucho rato.[n][w][e]

[msg MND_E14130100_CHK_TOILET_2]
[s][vp 1 0 0 0 0 0]Este es el baño de los chicos.[n][w][e]
[s][vp 1 0 0 0 0 0]Será mejor que me vaya. Alguien[n]podría hacerse una idea equivocada[n]si me quedo mucho rato.[n][w][e]

[msg MND_COMMON_CHK_TOILET_WO]
[s][vp 1 0 0 0 0 0]Este es el baño de los chicos.[n][w][e]
[s][vp 1 0 0 0 0 0]Será mejor que me vaya. Alguien[n]podría hacerse una idea equivocada[n]si me quedo mucho rato.[n][w][e]
