[msg MSG_008_0_0 [Ryuji]]
[s][f 5 14]¡Estáis guapísimas![n][w][e]

[msg MSG_009_0_0 [Makoto]]
[s][f 5 14]Me alegra que lo digas. Quedamos en hacernos[n]una foto con los kimonos.[n][w][e]

[msg MSG_010_0_0 [Ann]]
[s][f 5 14]Quizá deberíamos hacernos una de[n]grupo la próxima vez.[n][w][e]

[msg MSG_011_0_0 [Yusuke]]
[s][f 5 14]Esa foto es buena a su manera.[n]Creo que sí podría propiciar[n]buenos sueños.[n][w][e]

[msg MSG_012_0_0 [Ryuji]]
[s][f 5 14]Pero tienes que soñar con cosas[n]concretas si quieres tener[n]un buen año, ¿no?[n][w][e]


